### ISSUE TITLE
安装hexo-helper-qrcode 后，设置qrcode: true 后报错。

### ISSUE THREAD

**Issue by WeihuaGu** [viosey/hexo-theme-material#135]
hexo 根目录node_modules中易经成功安装hexo-helper-qrcode。
然后在主题的_config.yml中设置
qrcode: true后 hexo g后报错：
```
Unhandled rejection TypeError: /home/better/blog/themes/material/layout/post.ejs:59
    57|                 <% if(theme.scheme === 'Paradox') { %>
    58|                     <!-- Paradox Post Info -->
 >> 59|                     <%- partial('_partial/Paradox-post-info') %>
    60|                 <% } %>
    61| 
    62|                 <!-- Post Content -->

/home/better/blog/themes/material/layout/_partial/Paradox-post-info.ejs:31
    29|         <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="article-functions-qrcode-button">
    30|             <li class="mdl-menu__item"><%= __('post.qrcode') %></li>
 >> 31|             <img src="<%- qrcode(url, {
    32|                  margin: 2
    33|             }) %>">
    34|         </ul>

Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/home/better/blog/node_modules/hexo-helper-qrcode/index.js:4:21)
    at Object.wrapper [as qrcode] (/home/better/blog/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:1507)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:177)
    at /home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/better/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/better/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/better/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/better/blog/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:2561)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:3523)
    at /home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/better/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/better/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/better/blog/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/better/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:320:10)
    at RouteStream.Readable.on (_stream_readable.js:701:14)
    at RouteStream.Readable.pipe (_stream_readable.js:556:10)
    at /home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:166:23
    at Promise._execute (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at pipeStream (/home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:161:10)
    at writeFile (/home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:50:12)
    at fs.exists.then.finally.generatingFiles.(anonymous function) (/home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:36:42)
    at tryCatcher (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:415:13)

Unhandled rejection TypeError: /home/better/blog/themes/material/layout/post.ejs:59
    57|                 <% if(theme.scheme === 'Paradox') { %>
    58|                     <!-- Paradox Post Info -->
 >> 59|                     <%- partial('_partial/Paradox-post-info') %>
    60|                 <% } %>
    61| 
    62|                 <!-- Post Content -->

/home/better/blog/themes/material/layout/_partial/Paradox-post-info.ejs:31
    29|         <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="article-functions-qrcode-button">
    30|             <li class="mdl-menu__item"><%= __('post.qrcode') %></li>
 >> 31|             <img src="<%- qrcode(url, {
    32|                  margin: 2
    33|             }) %>">
    34|         </ul>

Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/home/better/blog/node_modules/hexo-helper-qrcode/index.js:4:21)
    at Object.wrapper [as qrcode] (/home/better/blog/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:1507)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:177)
    at /home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/better/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/better/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/better/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/better/blog/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:2561)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:3523)
    at /home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/better/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/better/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/better/blog/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/better/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:320:10)
    at RouteStream.Readable.on (_stream_readable.js:701:14)
    at RouteStream.Readable.pipe (_stream_readable.js:556:10)
    at /home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:166:23
    at Promise._execute (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at pipeStream (/home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:161:10)
    at writeFile (/home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:50:12)
    at fs.exists.then.finally.generatingFiles.(anonymous function) (/home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:36:42)
    at tryCatcher (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:415:13)

Unhandled rejection TypeError: /home/better/blog/themes/material/layout/post.ejs:59
    57|                 <% if(theme.scheme === 'Paradox') { %>
    58|                     <!-- Paradox Post Info -->
 >> 59|                     <%- partial('_partial/Paradox-post-info') %>
    60|                 <% } %>
    61| 
    62|                 <!-- Post Content -->

/home/better/blog/themes/material/layout/_partial/Paradox-post-info.ejs:31
    29|         <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="article-functions-qrcode-button">
    30|             <li class="mdl-menu__item"><%= __('post.qrcode') %></li>
 >> 31|             <img src="<%- qrcode(url, {
    32|                  margin: 2
    33|             }) %>">
    34|         </ul>

Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/home/better/blog/node_modules/hexo-helper-qrcode/index.js:4:21)
    at Object.wrapper [as qrcode] (/home/better/blog/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:1507)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:36:177)
    at /home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/better/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/better/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/better/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/better/blog/node_modules/hexo/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:2561)
    at eval (eval at <anonymous> (/home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:29:3523)
    at /home/better/blog/node_modules/hexo-renderer-ejs/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/better/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/better/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/better/blog/node_modules/hexo/lib/hexo/index.js:387:25
    at tryCatcher (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at /home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/better/blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:320:10)
    at RouteStream.Readable.on (_stream_readable.js:701:14)
    at RouteStream.Readable.pipe (_stream_readable.js:556:10)
    at /home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:166:23
    at Promise._execute (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/debuggability.js:300:9)
    at Promise._resolveFromExecutor (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:481:18)
    at new Promise (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:77:14)
    at pipeStream (/home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:161:10)
    at writeFile (/home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:50:12)
    at fs.exists.then.finally.generatingFiles.(anonymous function) (/home/better/blog/node_modules/hexo/lib/plugins/console/generate.js:36:42)
    at tryCatcher (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:143:10)
    at Async.drainQueues (/home/better/blog/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:415:13)

Unhandled rejection TypeError: /home/better/blog/themes/material/layout/post.ejs:59
    57|                 <% if(theme.scheme === 'Paradox') { %>
    58|                     <!-- Paradox Post Info -->
 >> 59|                     <%- partial('_partial/Paradox-post-info') %>
    60|                 <% } %>
    61| 
    62|                 <!-- Post Content -->

/home/better/blog/themes/material/layout/_partial/Paradox-post-info.ejs:31
    29|         <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple-effect" for="article-functions-qrcode-button">
    30|             <li class="mdl-menu__item"><%= __('post.qrcode') %></li>
 >> 31|             <img src="<%- qrcode(url, {
    32|                  margin: 2
    33|             }) %>">
    34|         </ul>

```

**Comment by cubesky** [comment]
您好，请查看下根目录的 package.json 中是否含有 hexo-helper-qrcode

**Comment by neoFelhz** [comment]
安装该插件时是否加了 --save？

**Comment by WeihuaGu** [comment]
@neoFelhz 加了 --save

**Comment by WeihuaGu** [comment]
@cubesky 有这个项目:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.2.2"
  },
  "dependencies": {
    "hexo": "^3.2.0",
    "hexo-deployer-git": "^0.2.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-renderer-ejs": "^0.2.0",
    "hexo-renderer-marked": "^0.2.10",
    "hexo-renderer-stylus": "^0.3.1",
    "hexo-server": "^0.2.0"
  }
}
```

**Comment by Halyul** [comment]
这个error我在我的vps上也遇到过 装了也没用 不知道啥问题 centos6

**Comment by WeihuaGu** [comment]
我觉得值得注意的错误是这行：
```
Object function Object() { [native code] } has no method 'assign'
    at Object.<anonymous> (/home/better/blog/node_modules/hexo-helper-qrcode/index.js:4:21)
```
我也不懂JavaScript原生对象是什么意思

**Comment by Halyul** [comment]
我回家之后看看我在Ubuntu上的配置 我在Ubuntu上的配置跟centos的配置一样而centos出错

**Comment by WeihuaGu** [comment]
@Halyul 我是ubuntu 15.10 32位。
npm@1.4.21 
hexo -V
hexo-cli: 1.0.2
os: Linux 4.2.0-42-generic linux ia32
http_parser: 1.0
node: 0.10.25
v8: 3.14.5.9
ares: 1.10.0
uv: 0.10.23
zlib: 1.2.8
modules: 11
openssl: 1.0.1f

**Comment by pidupuis** [comment]
Maybe use this [polyfill](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign#Polyfill) in a script tag somewhere in your head tag.

Could do the trick, haven't tested though

**Comment by WeihuaGu** [comment]
@pidupuis 

我在source/_data/head.yml中添加了这个pllyfill。qrcode: false,hexo g 通过，qrcode: true，还是报开始的那个错误。

pllyfill是不是这样添加的？

I added this pllyfill code to source / _data / head.yml. Qrcode: false, hexo g passed ; qrcode: true, reported that the beginning of the error.

How to add the pllyfill code  correctly?

```
Polyfill:
	'<script type="text/javascript">
		if (typeof Object.assign != "function") {
  				Object.assign = function(target) {
   							 "use strict";
   							 if (target == null) {
      							 throw new TypeError("Cannot convert undefined or null to object");
   							 }

                               target = Object(target);
                               for (var index = 1; index < arguments.length; index++) {
      					var source = arguments[index];
     					 if (source != null) {
       						 for (var key in source) {
         							 if (Object.prototype.hasOwnProperty.call(source, key)) {
           								 target[key] = source[key];
         							 }
       						 }
      					}
    				}
   			      return target;
 		 };
	</script>'
```

**Comment by WeihuaGu** [comment]
@pidupuis 
You mean  to added this pllyfill code to hexo-helper-qrcode/index.js?

**Comment by WeihuaGu** [comment]
在把 pllyfill 的代码加到hexo-helper-qrcode/index.js里后，Object function Object() { [native code] } has no method 'assign'消失了
但是出现了一系列`Object #<Object> has no method 'deflateSync'`这个错误。

**Comment by pidupuis** [comment]
I though here https://github.com/viosey/hexo-theme-material/blob/master/layout/_partial/head.ejs

But you seem to have more than one problem...

**Comment by WeihuaGu** [comment]
@pidupuis  in the head.ejs,i see a commit line of '-- UC Browser Compatible--'.so i add the pllyfill code in '<script> </script>
then test ,The problem remains。
You're right, there seem to more than one problem

**Comment by pidupuis** [comment]
Have you tried in a deployed system or have you tried locally?

Try to redo the all thing. From the root of your site, in a local dev environment:
```
npm uninstall hexo-helper-qrcode --save
npm install -g npm@latest
npm cache clean && npm install
npm install hexo-helper-qrcode --save
hexo clean && hexo generate && hexo server
```

**Comment by WeihuaGu** [comment]
tried locally,then copy the public_dir to deploy 。
redo uninstall hexo-helper-qrcode , update npm to latest,reinstall hexo-helper-qrcode,and clean hexo。
then hexo g ，the problem still remain.

**Comment by pidupuis** [comment]
Ok, have you specifically tried `hexo server`? (because you didn't mention it). But that's details, I don't think it would change anything though.

Try to update node:

```bash
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
```

By any chance, is there a public git repository for your blog so we could try by ourselves?

**Comment by pidupuis** [comment]
@WeihuaGu is this your blog? https://github.com/WeihuaGu/githubblog

It works for me. Here is what I did:

```bash
git clone https://github.com/WeihuaGu/githubblog.git
cd githubblog/
npm cache clean && npm install
npm install hexo-helper-qrcode --save
git clone https://github.com/viosey/hexo-theme-material.git themes/material/
```

I updated the `_config.yml` to set `public_dir: public`.
I updated the `themes/material/_config.yml` to set `qrcode: true`.

Then I did:

```bash
hexo clean && hexo generate && hexo server
```

And everything is ok for me.
```
Ubuntu 16.04.1 LTS
node v6.9.2
npm 3.10.8
```

So it could be a node version problem and/or a deploy problem...

**Comment by WeihuaGu** [comment]
@pidupuis  yes,this is my blog hexo folder git copy.
my ubuntu  version is 15.10
and npm is npm@4.1.1 /usr/local/lib/node_modules/npm
I guess is a node version problem or i use 32-bit system.
I run the setup_6.x,and it begin to update my apt source. some source can't be download ,and script Error executed.
```
W: 无法下载 http://ppa.launchpad.net/kilian/f.lux/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

W: 无法下载 http://ppa.launchpad.net/tualatrix/ppa/ubuntu/dists/wily/main/binary-i386/Packages  404  Not Found

E: 部分索引文件下载失败。如果忽略它们，那将转而使用旧的索引文件。
Error executing command, exiting
```

then 

```
aptitude show nodejs
软件包： nodejs                  
状态: 已安装
自动安装: 否
版本号： 0.10.25~dfsg2-2ubuntu1
优先级： 额外
部分： universe/web
维护者： Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
体系： i386
未压缩尺寸： 3,168 k
依赖于: libc-ares2 (>= 1.8.0), libc6 (>= 2.7), libgcc1 (>= 1:4.1.1), libssl1.0.0
     (>= 1.0.1), libstdc++6 (>= 4.1.1), libv8-3.14.5, zlib1g (>= 1:1.1.4)
描述： evented I/O for V8 javascript
 
主页： http://nodejs.org/
```
the node version i was too early

**Comment by pidupuis** [comment]
It seems that there is no nodejs 6 package for Ubuntu 15.10...

If you can't do `apt-get update` anymore, try:
```
sudo rm -r  /etc/apt/sources.list.d/nodesource.list
```

In any case, you have the 0.10 version. This is really old. Try to install nodejs 5 or more. If you can't use `curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -` because of your ubuntu version, try to upgrade nodejs manually by compiling the sources.

I'm sorry but your problem is outside the scope of the Material Hexo Theme. You'll have to fix your node version by yourself...

**Comment by WeihuaGu** [comment]
@pidupuis Thank you very much。I will  upgrade nodejs manually by compiling the sources. thank you again ：）
