### ISSUE TITLE
Unhandled rejection TypeError ~\themes\material\layout\layout.ejs

### ISSUE THREAD

**Issue by WaylanPunch** [viosey/hexo-theme-material#220]
详细错误：

```
Unhandled rejection TypeError: D:\WORKGROUP\GITHUB\waylanpunch.github.io\themes\material\layout\layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2346)
    at D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo-renderer-ejs\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\node_modules\bluebird\js\release\promise.js:510:31)
    at Promise._settlePromise (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\node_modules\bluebird\js\release\promise.js:567:18)
    at Promise._settlePromise0 (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\node_modules\bluebird\js\release\promise.js:612:10)
    at Promise._settlePromises (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\node_modules\bluebird\js\release\promise.js:691:18)
    at Async._drainQueue (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\WORKGROUP\GITHUB\waylanpunch.github.io\node_modules\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

看了 #4 和 #2 ，_config.template.yml 改成 _config.yml也不行 ：**Cannot read property 'substring' of null**

**Comment by loglife** [comment]
@WaylanPunch   直接在作者的仓库里复制或下载他的_config.template文件,之后将
_config.template改成 _config    , 在blog目录下打开git Bash  ,输入 hexo g 命令生成静态,  再hexo s完成后访问http://localhost:4000/即可

**Comment by WaylanPunch** [comment]
@loglife 好好，试一下

**Comment by Halyul** [comment]
能否将您的站点配置文件`  # Site`下的内容贴上来呢？

**Comment by EYHN** [comment]
看报错是站点配置文件的 language 属性没设置

**Comment by endday** [comment]
我尝试过修改lanuage属性为正确的，然后就轮到favicon图标构建报错，貌似是默认的config和主题不兼容

**Comment by Halyul** [comment]
@endday 你看看文本编码是什么 我遇到过这个问题 重新配置就好 千万不要复制粘贴

**Comment by WaylanPunch** [comment]
非常感谢@loglife 的建议，好了，另外@endday 我是重新建站点遇到和你一样的问题，用@loglife 的方法可行

**Comment by endday** [comment]
@Halyul 十分感谢，的确是因为这个原因
