### ISSUE TITLE
Cannot read property 'substring' of null

### ISSUE THREAD

**Issue by W-quan** [viosey/hexo-theme-material#235]
**I certify that I have first consulted** (check all with "x")

- [ ] [Hexo documentation](https://hexo.io/docs/)
- [ ] [Material theme documentation](https://material.viosey.com/)
- [x] [Material theme issues](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

**I'm submitting a**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request

```

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/wzq/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/wzq/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/wzq/blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/wzq/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/wzq/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/wzq/blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/wzq/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wzq/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/wzq/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/wzq/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/wzq/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/wzq/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/wzq/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/wzq/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:649:20)
    at tryOnImmediate (timers.js:622:5)
    at processImmediate [as _immediateCallback] (timers.js:594:5)
```

**Comment by EYHN** [comment]
请仔细阅读文档

**Comment by W-quan** [comment]
1. hexo init blog
2. git clone theme
3. cp _config.template.yml to _config.yml
4. change the "theme" of root's _config.yml to material
5. hexo s


我就是跟着文档来的 :unamused:

**Comment by EYHN** [comment]
@W-quan  文档是这个 https://material.viosey.com/

**Comment by W-quan** [comment]
然后是这个：https://material.viosey.com/start/

有错吗？

**Comment by EYHN** [comment]
基本设定的第一条语言

**Comment by neoFelhz** [comment]
If you don't read the docs and configure your config file carefully, we may close your issue with out check.

**Comment by W-quan** [comment]
好吧，我错了，没想到运行前提写在后面。

用后有点建议：

- entry_excerpt 的字数把Front-matter 也算进来了。我觉得应该排除；

- 阅读文章返回主页按钮，需要先展开侧栏，再点击主页，能不能加一个按钮或者直接把侧栏固定展开。像Google+ 那样。默认展开的

**Comment by neoFelhz** [comment]
- 这个 issue 应该给 Hexo 提。你也可以用  手动决定摘要
- #90
