### ISSUE TITLE
预览图很赞，但是主题有Bug，运行报错。

### ISSUE THREAD

**Issue by BTyang** [viosey/hexo-theme-material#242]
Unhandled rejection TypeError: /Users/Mr.Yang/Documents/BTyang/BTyang.github.io/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

GET / - - ms - -
08:56:24.336 DEBUG Rendering index: index.html
Unhandled rejection TypeError: /Users/Mr.Yang/Documents/BTyang/BTyang.github.io/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

GET / - - ms - -
08:58:24.370 DEBUG Rendering index: index.html
Unhandled rejection TypeError: /Users/Mr.Yang/Documents/BTyang/BTyang.github.io/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/Mr.Yang/Documents/BTyang/BTyang.github.io/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)

**Comment by cubesky** [comment]
请正确配置语言选项

**Comment by cubesky** [comment]
具体请阅读此处 https://material.viosey.com/start/
