### ISSUE TITLE
Unhandled rejection TypeError:

### ISSUE THREAD

**Issue by nianxiaoge** [viosey/hexo-theme-material#249]
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: C:\Users\xiaoge\hexo\themes\material\layout\index.ejs:6
```
    4|         <!-- Paradox Header -->
    5|         <%- partial('_partial/daily_pic') %>
 >> 6|         <%- partial('_partial/blog_info') %>
    7|     <% } %>
    8|     <div class="locate-thumbnail-symbol"></div>
    9|
```

C:\Users\xiaoge\hexo\themes\material\layout\_partial\blog_info.ejs:62
```
    60|             <% } %>
    61|
 >> 62|             <% if(theme.sns_share.weibo === true) { %>
    63|                 <a class="index_share-link" href="http://service.weibo.com/share/share.php?appkey=&title=<%= config.title %>&url=<%- config.url + config.root %>&pic=&searchPic=false&style=simple" target="_blank">
    64|                     <li class="mdl-menu__item mdl-js-ripple-effect">
    65|                         <%= __('share.toWeibo') %>
```

Cannot read property 'weibo' of undefined
    at eval (eval at <anonymous> (C:\Users\xiaoge\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:3307)
    at eval (eval at <anonymous> (C:\Users\xiaoge\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:7395)
    at C:\Users\xiaoge\hexo\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (C:\Users\xiaoge\hexo\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (C:\Users\xiaoge\hexo\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (C:\Users\xiaoge\hexo\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper (C:\Users\xiaoge\hexo\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (C:\Users\xiaoge\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:320)
    at eval (eval at <anonymous> (C:\Users\xiaoge\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:34:298)
    at C:\Users\xiaoge\hexo\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (C:\Users\xiaoge\hexo\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (C:\Users\xiaoge\hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at C:\Users\xiaoge\hexo\node_modules\hexo\lib\hexo\index.js:387:25
    at tryCatcher (C:\Users\xiaoge\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at C:\Users\xiaoge\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (C:\Users\xiaoge\hexo\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
    at resume_ (_stream_readable.js:737:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

**Comment by cubesky** [comment]
请正确配置 `_config.yml`

**Comment by neoFelhz** [comment]
请仔细阅读文档。
所有不阅读文档的 issue 都会被我们关闭。
