### ISSUE TITLE
Unhandled rejection TypeError: E:\myblog\themes\material\layout\layout.ejs:2

### ISSUE THREAD

**Issue by wubucheng** [viosey/hexo-theme-material#289]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

详细问题（执行hexo s --debug 时出现下列问题且无法打开localhost:4000)：
，是主题问题还是hexo的问题)：
Unhandled rejection TypeError: E:\myblog\themes\material\layout\layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (E:\myblog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (E:\myblog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2346)
    at E:\myblog\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (E:\myblog\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (E:\myblog\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\myblog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (E:\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\myblog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\myblog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\myblog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\myblog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\myblog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\myblog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\myblog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)

**Comment by EYHN** [comment]
这既不是hexo的问题也不是主题的问题。是你的配置问题！文档明确你需要设置hexo配置文件的 language 属性。以往的issue也有很多同样的问题，你完全没看。提高容错性的方案会在将来被更新 #275

**Comment by neoFelhz** [comment]
RTFM, thanks.
