### ISSUE TITLE
hexo s ERROR

### ISSUE THREAD

**Issue by WangChangQin** [viosey/hexo-theme-material#313]
```
$ hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: E:\myblog\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html lang="<%- config.language.substring(0,2) %>">
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

E:\myblog\themes\material\layout\_partial\head.ejs:40
    38|     <!-- dns prefetch -->
    39|     <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 40|     <% if(theme.materialcdn.use === true) { %>
    41|         <link rel="dns-prefetch" href="<%= theme.materialcdn.base %>"/>
    42|     <%}%>
    43|     <% if(theme.leancloud.enable === true) { %>

Cannot read property 'use' of undefined
    at eval (eval at exports.compile (E:\myblog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:49:464)
    at eval (eval at exports.compile (E:\myblog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:49:7946)
    at E:\myblog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (E:\myblog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (E:\myblog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (E:\myblog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (E:\myblog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (E:\myblog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:130)
    at eval (eval at exports.compile (E:\myblog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2346)
    at E:\myblog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiled (E:\myblog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (E:\myblog\node_modules\hexo\lib\theme\view.js:29:15)
    at E:\myblog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (E:\myblog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (E:\myblog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\myblog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (E:\myblog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (E:\myblog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (E:\myblog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (E:\myblog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (E:\myblog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
```

**Comment by neoFelhz** [comment]
RTFM.

**Comment by cubesky** [comment]
Please compare `_config.template.yml` and your `_config.yml` to solve **BREAK CHANGES**

**Comment by WangChangQin** [comment]
hexo s --debug can run,3ku
