### ISSUE TITLE
hexo g发生错误

### ISSUE THREAD

**Issue by err0x0000** [viosey/hexo-theme-material#317]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

```
使用hexo g时发生了如下的错误，该错误只在使用material主题时发生:
Unhandled rejection TypeError: /home/xi/Test/Blog/themes/material/layout/post.ejs:76
    74|                 <!-- Post Comments -->
    75|                 <% if(page.comment !== false) { %>
 >> 76|                     <%- partial('_partial/comment') %>
    77|                 <% } %>
    78|             </div>
    79| 

/home/xi/Test/Blog/themes/material/layout/_partial/comment.ejs:1
 >> 1| <% if(theme.comment.use === 'duoshuo') { %>
    2|     <!-- 使用多说评论 -->
    3|     <%- partial('_widget/duoshuo') %>
    4| <% } %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:49)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:1351)
    at /home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/xi/Test/Blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/xi/Test/Blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:3573)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:3869)
    at /home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/xi/Test/Blog/node_modules/hexo/lib/hexo/index.js:388:25
    at tryCatcher (/home/xi/Test/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at /home/xi/Test/Blog/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/xi/Test/Blog/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:349:10)
    at resume_ (_stream_readable.js:738:12)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

Unhandled rejection TypeError: /home/xi/Test/Blog/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html lang="<%- config.language.substring(0,2) %>">
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

/home/xi/Test/Blog/themes/material/layout/_partial/head.ejs:40
    38|     <!-- dns prefetch -->
    39|     <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 40|     <% if(theme.materialcdn.use === true) { %>
    41|         <link rel="dns-prefetch" href="<%= theme.materialcdn.base %>"/>
    42|     <%}%>
    43|     <% if(theme.leancloud.enable === true) { %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:464)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:7946)
    at /home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/xi/Test/Blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/xi/Test/Blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:130)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/xi/Test/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)

Unhandled rejection TypeError: /home/xi/Test/Blog/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html lang="<%- config.language.substring(0,2) %>">
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

/home/xi/Test/Blog/themes/material/layout/_partial/head.ejs:40
    38|     <!-- dns prefetch -->
    39|     <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 40|     <% if(theme.materialcdn.use === true) { %>
    41|         <link rel="dns-prefetch" href="<%= theme.materialcdn.base %>"/>
    42|     <%}%>
    43|     <% if(theme.leancloud.enable === true) { %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:464)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:7946)
    at /home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/xi/Test/Blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/xi/Test/Blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:130)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/xi/Test/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)

Unhandled rejection TypeError: /home/xi/Test/Blog/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html lang="<%- config.language.substring(0,2) %>">
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

/home/xi/Test/Blog/themes/material/layout/_partial/head.ejs:40
    38|     <!-- dns prefetch -->
    39|     <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 40|     <% if(theme.materialcdn.use === true) { %>
    41|         <link rel="dns-prefetch" href="<%= theme.materialcdn.base %>"/>
    42|     <%}%>
    43|     <% if(theme.leancloud.enable === true) { %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:464)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:7946)
    at /home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/xi/Test/Blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/xi/Test/Blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:130)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/xi/Test/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)

Unhandled rejection TypeError: /home/xi/Test/Blog/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html lang="<%- config.language.substring(0,2) %>">
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

/home/xi/Test/Blog/themes/material/layout/_partial/head.ejs:40
    38|     <!-- dns prefetch -->
    39|     <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 40|     <% if(theme.materialcdn.use === true) { %>
    41|         <link rel="dns-prefetch" href="<%= theme.materialcdn.base %>"/>
    42|     <%}%>
    43|     <% if(theme.leancloud.enable === true) { %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:464)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:7946)
    at /home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/xi/Test/Blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/xi/Test/Blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:130)
    at eval (eval at <anonymous> (/home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /home/xi/Test/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/xi/Test/Blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/xi/Test/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/xi/Test/Blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/xi/Test/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:570:20)
```

**Comment by neoFelhz** [comment]
Plz read the docs and check whether you have change the config-file's name form `_config.template.yml` to `_config.yml`

**Comment by err0x0000** [comment]
感谢，问题已解决
