### ISSUE TITLE
下载最新的主题之后，按照文档进行了修改，但是在hexo g时，报错了，怎么解决呢

### ISSUE THREAD

**Issue by MichaelXoX** [viosey/hexo-theme-material#321]
下载最新的主题之后，按照文档进行了修改，但是在hexo g时，报错了。
```
Unhandled rejection TypeError: D:\OneDrive\备忘文档\BLOG-T\themes\material\layout\layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (D:\OneDrive\备忘文档\BLOG-T\node_modules\ejs\lib\ejs.js:242:14), <anonym
ous>:30:79)
    at eval (eval at <anonymous> (D:\OneDrive\备忘文档\BLOG-T\node_modules\ejs\lib\ejs.js:242:14), <anonym
ous>:30:2346)
    at D:\OneDrive\备忘文档\BLOG-T\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\OneDrive\备忘文档\BLOG-T\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\OneDrive\备忘文档\BLOG-T\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\OneDrive\备忘文档\BLOG-T\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\OneDrive\备忘文档\BLOG-T\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\OneDrive\备忘文档\BLOG-T\node_modules\bluebird\js\release\pro
mise.js:512:31)
    at Promise._settlePromise (D:\OneDrive\备忘文档\BLOG-T\node_modules\bluebird\js\release\promise.js:569
:18)
    at Promise._settlePromise0 (D:\OneDrive\备忘文档\BLOG-T\node_modules\bluebird\js\release\promise.js:61
4:10)
    at Promise._settlePromises (D:\OneDrive\备忘文档\BLOG-T\node_modules\bluebird\js\release\promise.js:69
3:18)
    at Async._drainQueue (D:\OneDrive\备忘文档\BLOG-T\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\OneDrive\备忘文档\BLOG-T\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\OneDrive\备忘文档\BLOG-T\node_modules\bluebird\js\release\async.js:
17:14)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
```

**Comment by cubesky** [comment]
请认真阅读 https://material.viosey.com 文档，或查询历史 Issue #235

**Comment by MichaelXoX** [comment]
那我建议一下，基本设定，设置语言，这个顺序应该调整到你们文档的 hexo s之前，毕竟刚刚我是按照流程来操作的，当执行hexo s时，因为还没设置之后的语言，才发生了这个错误，调整顺序之后，将避免这个错了

**Comment by cubesky** [comment]
@MichaelXoX 目前的开发分支已经适配未设置语言的情况，下一个版本正在开发中，我们将择期发布。
感谢您的使用 (*^_^*)

**Comment by neoFelhz** [comment]
https://material-org.viosey.com/start/

这是文档的第一句话和第二句话：


在使用 「Material」主题之前，请仔细阅读 Hexo 的官方文档，完成对 Hexo 的安装和基本的配置。
在本文档中，我们假定你已经成功安装了 Hexo，并根据 Hexo 的文档创建了一个站点，并完成了基本的设置。

----

只能说你没有认真读文档。。。

**Comment by viosey** [comment]
请详细阅读文档，并培养阅读文档与搜索习惯，而不是作为「伸手党」
而且已经单独列出了常见问题目录：https://material.viosey.com/faq/
