### ISSUE TITLE
报错啊

### ISSUE THREAD

**Issue by xujianhui404** [viosey/hexo-theme-material#348]
```
Unhandled rejection TypeError: /Users/userName/Documents/blogdisk/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Unhandled rejection TypeError: /Users/userName/Documents/blogdisk/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Unhandled rejection TypeError: /Users/userName/Documents/blogdisk/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Unhandled rejection TypeError: /Users/userName/Documents/blogdisk/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Unhandled rejection TypeError: /Users/userName/Documents/blogdisk/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Unhandled rejection TypeError: /Users/userName/Documents/blogdisk/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

Unhandled rejection TypeError: /Users/userName/Documents/blogdisk/themes/material/layout/layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (/Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2346)
    at /Users/userName/Documents/blogdisk/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/userName/Documents/blogdisk/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/userName/Documents/blogdisk/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
```

**Comment by neoFelhz** [comment]
Please read the fucking docs!
