### ISSUE TITLE
links.yml 问题

### ISSUE THREAD

**Issue by 13633254201** [viosey/hexo-theme-material#36]
Name: fir.im
    link: http://blog.izgq.net/
    avatar: http://img.ptcms.csdn.net/article/201601/08/568f37886d0a3.jpg
    descr: "aa"

error:
ERROR Process failed: _data/links.yml
YAMLException: bad indentation of a mapping entry at line 2, column 10:
         link: http://blog.izgq.net/
             ^
    at generateError (/root/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:162:10)
    at throwError (/root/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:168:9)
    at readBlockMapping (/root/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1075:7)
    at composeNode (/root/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1327:12)
    at readDocument (/root/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1489:3)
    at loadDocuments (/root/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1545:5)
    at Object.load (/root/hexo/node_modules/hexo/node_modules/js-yaml/lib/js-yaml/loader.js:1562:19)
    at Hexo.yamlHelper (/root/hexo/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/method.js:15:34)
    at /root/hexo/node_modules/hexo/lib/hexo/render.js:61:21
    at tryCatcher (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Async.drainQueues (/root/hexo/node_modules/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at process._tickCallback (node.js:458:13)

**Comment by viosey** [comment]
请参考 [友情链接：添加数据](https://material.vss.im/compose/#添加数据) 的格式，
你的缩进错了。
