### ISSUE TITLE
请问本地预览出现这样怎么回事，预览本地不出现

### ISSUE THREAD

**Issue by liu-ziming** [viosey/hexo-theme-material#368]
$ hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: D:\hexo\themes\material\layout\layout.ejs:2
    1| <!DOCTYPE html>
 >> 2| <html lang="<%- config.language.substring(0,2) %>">
    3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>

Cannot read property 'substring' of null
    at eval (eval at <anonymous> (D:\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:79)
    at eval (eval at <anonymous> (D:\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2346)
    at D:\hexo\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (D:\hexo\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (D:\hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\hexo\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\hexo\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\hexo\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\hexo\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\hexo\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\hexo\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\hexo\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\hexo\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)

**Comment by neoFelhz** [comment]
Before you open a new issue, please read the doc scarefully and recheck your configuration.
