### ISSUE TITLE
Can't generate,the layout maybe have something wrong

### ISSUE THREAD

**Issue by fwgood** [viosey/hexo-theme-material#374]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

```
$ hexo generate
     (node:7420) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
INFO  Files loaded in 330 ms
Unhandled rejection TypeError: I:\repo\hexo\fwgood\themes\hexo-material\layout\post.ejs:44
    42|                 <!-- Post Comments -->
    43|                 <% if(page.comment !== false) { %>
 >> 44|                     <%- partial('_partial/comment') %>
    45|                 <% } %>
    46|             </div>
    47|
I:\repo\hexo\fwgood\themes\hexo-material\layout\_partial\comment.ejs:1
 >> 1| <% if(theme.comment.use) { %>
    2|     <%- partial('_widget/comment/' + theme.comment.use + '/enter') %>
    3| <% } %>

Cannot read property 'use' of undefined
    at eval (eval at exports.compile (I:\repo\hexo\fwgood\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:49)
    at eval (eval at exports.compile (I:\repo\hexo\fwgood\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:204)
    at I:\repo\hexo\fwgood\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (I:\repo\hexo\fwgood\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (I:\repo\hexo\fwgood\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (I:\repo\hexo\fwgood\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (I:\repo\hexo\fwgood\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (I:\repo\hexo\fwgood\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:1982)
    at eval (eval at exports.compile (I:\repo\hexo\fwgood\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2278)
    at I:\repo\hexo\fwgood\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiled (I:\repo\hexo\fwgood\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (I:\repo\hexo\fwgood\node_modules\hexo\lib\theme\view.js:29:15)
    at I:\repo\hexo\fwgood\node_modules\hexo\lib\hexo\index.js:390:25
    at tryCatcher (I:\repo\hexo\fwgood\node_modules\bluebird\js\release\util.js:16:23)
    at I:\repo\hexo\fwgood\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (I:\repo\hexo\fwgood\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:429:10)
    at resume_ (_stream_readable.js:809:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

Unhandled rejection TypeError: I:\repo\hexo\fwgood\themes\hexo-material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->
```

**Comment by neoFelhz** [comment]
**RTFM, please!**
Of course you haven't read the docs, at all.
- https://material.viosey.com/en/start/
- https://material.viosey.com/start/
