### ISSUE TITLE
有一个错误

### ISSUE THREAD

**Issue by wimvogt** [viosey/hexo-theme-material#394]
```
Unhandled rejection ReferenceError: /Users/wim/hexo/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

/Users/wim/hexo/themes/material/layout/_partial/head.ejs:161
    159|         <%- jsLsload({path:(theme.materialcdn.base + '/js/jquery.min.js'),key:'js/jquery.min.js'}) %>
    160|     <%}else{%>
 >> 161|         <%- cssLsload('css/material.min.css') %>
    162|         <%- cssLsload('css/style.min.css') %>
    163|         <% if(theme.scheme === 'Isolation') { %>
    164|             <%- cssLsload('/css/fontawesome.min.css') %>

cssLsload is not defined
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:16218)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:18043)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:252)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2468)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/wim/hexo/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/wim/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/wim/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/wim/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/wim/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Unhandled rejection ReferenceError: /Users/wim/hexo/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

/Users/wim/hexo/themes/material/layout/_partial/head.ejs:161
    159|         <%- jsLsload({path:(theme.materialcdn.base + '/js/jquery.min.js'),key:'js/jquery.min.js'}) %>
    160|     <%}else{%>
 >> 161|         <%- cssLsload('css/material.min.css') %>
    162|         <%- cssLsload('css/style.min.css') %>
    163|         <% if(theme.scheme === 'Isolation') { %>
    164|             <%- cssLsload('/css/fontawesome.min.css') %>

cssLsload is not defined
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:16218)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:18043)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:252)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2468)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/wim/hexo/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/wim/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/wim/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/wim/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/wim/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Unhandled rejection ReferenceError: /Users/wim/hexo/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

/Users/wim/hexo/themes/material/layout/_partial/head.ejs:161
    159|         <%- jsLsload({path:(theme.materialcdn.base + '/js/jquery.min.js'),key:'js/jquery.min.js'}) %>
    160|     <%}else{%>
 >> 161|         <%- cssLsload('css/material.min.css') %>
    162|         <%- cssLsload('css/style.min.css') %>
    163|         <% if(theme.scheme === 'Isolation') { %>
    164|             <%- cssLsload('/css/fontawesome.min.css') %>

cssLsload is not defined
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:16218)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:18043)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wim/hexo/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/Users/wim/hexo/node_modules/lodash/lodash.js:4962:19)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:252)
    at eval (eval at <anonymous> (/Users/wim/hexo/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2468)
    at /Users/wim/hexo/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/Users/wim/hexo/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/wim/hexo/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/wim/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (/Users/wim/hexo/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (/Users/wim/hexo/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (/Users/wim/hexo/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/wim/hexo/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by neoFelhz** [comment]
Please check your theme folder, then rename the `_config/template.yml` to `_config.yml`

**Comment by wimvogt** [comment]
I have already renamed it

**Comment by neoFelhz** [comment]
Check whether there is a `script` folder in your theme dir.

**Comment by BENZJ** [comment]
I have the same problem , I have already rename the _config.temple.yml to _config.temple. 

my system is win10 linux subsystem.  
material version is 1.5.2
