### ISSUE TITLE
更换主题后，报错了Unhandled rejection TypeError: themes/material/layout/layout.ejs:5

### ISSUE THREAD

**Issue by gai123** [viosey/hexo-theme-material#4]
修改hexo主题之后，执行hexo s -g , 访问http://localhost:4000/，终端显示以下log∑っ°Д;)っ ，麻烦作者看看，
另外，主题好漂亮，阿里嘎多 (●°u°●)」 ，已star，fork

Unhandled rejection TypeError: ~/Blog/themes/material/layout/layout.ejs:5
    3|     <%- partial('_partial/head') %>
    4|
 >> 5|     <body id="scheme-<%= theme.style.scheme %>">
    6|         <div class="material-layout  mdl-js-layout has-drawer is-upgraded">
    7|             
    8|             <main class="material-layout__content" id="main">

Cannot read property 'scheme' of undefined
    at eval (eval at <anonymous> (~/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:159)
    at eval (eval at <anonymous> (~/Blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:884)
    at ~/Blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (~/Blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (~/Blog/node_modules/hexo/lib/theme/view.js:29:15)
    at ~/Blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (~/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (~/Blog/node_modules/bluebird/js/release/promise.js:510:31)
    at Promise._settlePromise (~/Blog/node_modules/bluebird/js/release/promise.js:567:18)
    at Promise._settlePromise0 (~/Blog/node_modules/bluebird/js/release/promise.js:612:10)
    at Promise._settlePromises (~/Blog/node_modules/bluebird/js/release/promise.js:691:18)
    at Async._drainQueue (~/Blog/node_modules/bluebird/js/release/async.js:138:16)
    at Async._drainQueues (~/Blog/node_modules/bluebird/js/release/async.js:148:10)
    at Immediate.Async.drainQueues [as _onImmediate] (~/Blog/node_modules/bluebird/js/release/async.js:17:14)
    at tryOnImmediate (timers.js:543:15)
    at processImmediate [as _immediateCallback] (timers.js:523:5)

WARN  Partial _widget/head_custom does not exist. (in _partial/head.ejs)
Unhandled rejection TypeError: ~/Blog/themes/material/layout/layout.ejs:5

**Comment by viosey** [comment]
那个，你使用主题的版本是最新的吗？
或者主题文件夹下面的 `_config.example.yml` 的 `.example` 有删除掉吗？

**Comment by viosey** [comment]
如果还是不行的话，我今天中午会更新一次，到时候可以更新最新版本哒。

**Comment by renmay** [comment]
Unhandled rejection TypeError: /Users/renmay/hexoBlog/themes/hexo-theme-material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

/Users/renmay/hexoBlog/themes/hexo-theme-material/layout/_partial/head.ejs:20
    18|
    19|     
 >> 20|     <%- partial('_widget/dnsprefetch') %>
    21|
    22|     
    23|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

/Users/renmay/hexoBlog/themes/hexo-theme-material/layout/_widget/dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>

Cannot read property 'materialcdn' of undefined
    at eval (eval at compile (/Users/renmay/hexoBlog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:25)
    at returnedFn (/Users/renmay/hexoBlog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/Users/renmay/hexoBlog/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/Users/renmay/hexoBlog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/renmay/hexoBlog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/Users/renmay/hexoBlog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/Users/renmay/hexoBlog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (/Users/renmay/hexoBlog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/Users/renmay/hexoBlog/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/Users/renmay/hexoBlog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/renmay/hexoBlog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/Users/renmay/hexoBlog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/Users/renmay/hexoBlog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/Users/renmay/hexoBlog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled (/Users/renmay/hexoBlog/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/Users/renmay/hexoBlog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/renmay/hexoBlog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/renmay/hexoBlog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/renmay/hexoBlog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/renmay/hexoBlog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/renmay/hexoBlog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/renmay/hexoBlog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/renmay/hexoBlog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/renmay/hexoBlog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/renmay/hexoBlog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:773:18)
    at tryOnImmediate (timers.js:734:5)
    at processImmediate [as _immediateCallback] (timers.js:711:5)

**Comment by Y-JINHAO** [comment]
INFO  Files loaded in 4.56 s
ERROR TypeError: D:\frontEnd\练习\blog\white-dust\themes\Butterfly\layout\includes\page\flink.pug:13
    11|           .flink-desc!=i.class_desc
    12|         .flink-list
  > 13|           each item in i.link_list
    14|             .flink-list-item
    15|               a(href=url_for(item.link)  title=item.name target="_blank")
    16|                 if theme.lazyload.enable

Cannot read property 'length' of undefined
    at eval (eval at wrap (D:\frontEnd\练习\blog\white-dust\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:850:32)
    at eval (eval at wrap (D:\frontEnd\练习\blog\white-dust\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:903:4)
    at eval (eval at wrap (D:\frontEnd\练习\blog\white-dust\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:908:4)
    at template (eval at wrap (D:\frontEnd\练习\blog\white-dust\node_modules\pug-runtime\wrap.js:6:10), <anonymous>:4111:93)
    at _View._compiled (D:\frontEnd\练习\blog\white-dust\node_modules\hexo\lib\theme\view.js:136:50)
    at _View.render (D:\frontEnd\练习\blog\white-dust\node_modules\hexo\lib\theme\view.js:39:17)
    at D:\frontEnd\练习\blog\white-dust\node_modules\hexo\lib\hexo\index.js:64:21
    at tryCatcher (D:\frontEnd\练习\blog\white-dust\node_modules\bluebird\js\release\util.js:16:23)
    at D:\frontEnd\练习\blog\white-dust\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (D:\frontEnd\练习\blog\white-dust\node_modules\hexo\lib\hexo\router.js:47:5)
    at RouteStream.Readable.read (_stream_readable.js:468:10)
    at resume_ (_stream_readable.js:982:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  path: 'D:\\frontEnd\\练习\\blog\\white-dust\\themes\\Butterfly\\layout\\includes\\page\\flink.pug'
}
我报了这个错，怎么解决呀，友情链接进不去

**Comment by KnightKilito** [comment]
时隔多年我也出现了这个错误qwq
新人第一次摸索hexo，如果解决不了那我只能换个主题了呜呜呜

Unhandled rejection TypeError: /usr/local/hexoblog/themes/hexo-theme-material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

/usr/local/hexoblog/themes/hexo-theme-material/layout/_partial/head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

/usr/local/hexoblog/themes/hexo-theme-material/layout/_widget/dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>

Cannot read property 'materialcdn' of undefined
    at eval (/usr/local/hexoblog/themes/hexo-theme-material/layout/_widget/dnsprefetch.ejs:12:25)
    at dnsprefetch (/usr/local/hexoblog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/usr/local/hexoblog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/usr/local/hexoblog/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/usr/local/hexoblog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (/usr/local/hexoblog/themes/hexo-theme-material/layout/_partial/head.ejs:12:17)
    at head (/usr/local/hexoblog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiledSync (/usr/local/hexoblog/node_modules/hexo/lib/theme/view.js:132:24)
    at _View.renderSync (/usr/local/hexoblog/node_modules/hexo/lib/theme/view.js:59:25)
    at Object.partial (/usr/local/hexoblog/node_modules/hexo/lib/plugins/helper/partial.js:34:15)
    at eval (/usr/local/hexoblog/themes/hexo-theme-material/layout/layout.ejs:19:17)
    at layout (/usr/local/hexoblog/node_modules/ejs/lib/ejs.js:682:17)
    at _View._compiled (/usr/local/hexoblog/node_modules/hexo/lib/theme/view.js:136:50)
    at _View.render (/usr/local/hexoblog/node_modules/hexo/lib/theme/view.js:39:17)
    at /usr/local/hexoblog/node_modules/hexo/lib/theme/view.js:51:25
    at tryCatcher (/usr/local/hexoblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/usr/local/hexoblog/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/usr/local/hexoblog/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/usr/local/hexoblog/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/usr/local/hexoblog/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/usr/local/hexoblog/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/usr/local/hexoblog/node_modules/bluebird/js/release/async.js:86:9)

**Comment by KnightKilito** [comment]
我本来也报这个错，本以为有issue有更新应该没问题，查了文档发现还是得对下载的主题进行初始配置，这边留个指引给后来人（毕竟我就是百度了回到这个issue的……我原以为是我服务器的问题……）：
**_“为防止造成冲突，主题以 _config.template.yml 文件取代 _config.yml 文件，用以参考配置。 **需要手动将 material （你下载的主题文件夹名称）文件夹中的 _config.template.yml 复制一份并重命名为 _config.yml**。”_**

https://neko-dev.github.io/material-theme-docs/#/zh-cn/setup（官方文档）
