### ISSUE TITLE
'hexo clean' 404 file

### ISSUE THREAD

**Issue by kmahyyg** [viosey/hexo-theme-material#410]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

> kmahyyg:~/workspace/kmahyyg.github.io (master) $ hexo clean
ERROR Script load failed: themes/material/scripts/helper.js
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:53:16)
    at /home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/lib/hexo/index.js:228:17
    at tryCatcher (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at /home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)

**Comment by kmahyyg** [comment]
Download from the releases page on github.
All needed plugins are installed.

> kmahyyg:~/workspace/kmahyyg.github.io/themes/material (master) $ npm install
npm WARN unmet dependency /home/ubuntu/workspace/kmahyyg.github.io/themes/material/node_modules/sass-lint requires eslint@'^2.7.0' but will load
npm WARN unmet dependency /home/ubuntu/workspace/kmahyyg.github.io/themes/material/node_modules/eslint,
npm WARN unmet dependency which is version 3.19.0

> kmahyyg:~/workspace/kmahyyg.github.io (master) $ cat ./package.json 
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "hexo": {
    "version": "3.3.1"
  },
  "dependencies": {
    "ejs": "^2.5.5",
    "ejs-lint": "^0.2.0",
    "hexo": "^3.3.1",
    "hexo-cli": "^1.0.1",
    "hexo-deployer-git": "^0.1.0",
    "hexo-generator-archive": "^0.1.4",
    "hexo-generator-category": "^0.1.3",
    "hexo-generator-feed": "^1.2.0",
    "hexo-generator-index": "^0.2.0",
    "hexo-generator-search": "^1.0.2",
    "hexo-generator-tag": "^0.2.0",
    "hexo-helper-qrcode": "^1.0.2",
    "hexo-renderer-ejs": "^0.1.1",
    "hexo-renderer-marked": "^0.2.9",
    "hexo-renderer-stylus": "^0.3.0",
    "hexo-search": "^1.0.3",
    "hexo-server": "^0.1.3",
    "hexo-prism-plugin": "^2.1.2"
  }
}

**Comment by EYHN** [comment]
node版本太低

**Comment by kmahyyg** [comment]
@EYHN nodejs -v  0.10.25
npm -v 2.15.1

apt-get install提示已经是newest

**Comment by EYHN** [comment]
apt安装node需要加官方软件源 详情见官网文档 推荐使用nvm工具安装

**Comment by EYHN** [comment]
最新版本 node8.1.2

**Comment by kmahyyg** [comment]
@EYHN 好吧，的确太老，v4.43

**Comment by kmahyyg** [comment]
@EYHN 

按照nodejs.org的官方的一键装了最新的nodejs，还是不行

> kmahyyg:~/workspace/kmahyyg.github.io (master) $ hexo clean
ERROR Script load failed: themes/material/scripts/helper.js
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:53:16)
    at /home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/lib/hexo/index.js:230:17
    at tryCatcher (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at /home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/bluebird/js/release/nodeback.js:42:21
    at /home/ubuntu/workspace/kmahyyg.github.io/node_modules/hexo/node_modules/hexo-fs/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
INFO  Deleted database.

**Comment by EYHN** [comment]
node版本号？ 看报错依旧是无法解析es6的解构语法

**Comment by EYHN** [comment]
node版本必须大于6.0

**Comment by EYHN** [comment]
运行 `node -v` 获取版本号

**Comment by kmahyyg** [comment]
@EYHN apt list --installed | grep nodejs 提示8.1.2

node -v提示 4.4.3


环境: cloud9 webide

**Comment by kmahyyg** [comment]
```nvm install 6
nvm alias default 6```

两条命令解决

**Comment by kmahyyg** [comment]
nvm install 6
