### ISSUE TITLE
config.url.replace is not a function

### ISSUE THREAD

**Issue by Odinysus** [viosey/hexo-theme-material#441]
在将thems/Material/_config.template.yml替换config.yml.结果报一下错误
```
TypeError: config.url.replace is not a function
    at /Users/buxiqiang/project/github/myblog/node_modules/hexo/lib/hexo/load_config.js:35:29
    at tryCatcher (/Users/buxiqiang/project/github/myblog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/buxiqiang/project/github/myblog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/buxiqiang/project/github/myblog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/buxiqiang/project/github/myblog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/buxiqiang/project/github/myblog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/buxiqiang/project/github/myblog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/buxiqiang/project/github/myblog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/buxiqiang/project/github/myblog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
```

**Comment by xclidongbo** [comment]
me too.

**Comment by kingcucu** [comment]
D:\Blog
λ  hexo server
FATAL config.url.replace is not a function
TypeError: config.url.replace is not a function
    at fs.exists.then.then.then.config (D:\Blog\node_modules\hexo\lib\hexo\load_config.js:35:29)
    at tryCatcher (D:\Blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\Blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\Blog\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\Blog\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:794:20)
    at tryOnImmediate (timers.js:752:5)
    at processImmediate [as _immediateCallback] (timers.js:729:5)

How to deal with it
