### ISSUE TITLE
创建时间轴和相册标签云报错 ERROR Theme config load failed. ERROR Process failed: _config.yml

### ISSUE THREAD

**Issue by tiakia** [viosey/hexo-theme-material#450]
```
 hexo s
(node:8380) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
ERROR Theme config load failed.
ERROR Process failed: _config.yml
Error
    at generateError (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1080:7)
    at composeNode (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readBlockMapping (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1062:11)
    at composeNode (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readBlockMapping (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1062:11)
    at composeNode (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at Object.load (G:\blog\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Hexo.yamlHelper (G:\blog\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (G:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (G:\blog\node_modules\bluebird\js\release\method.js:15:34)
    at G:\blog\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (G:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (G:\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (G:\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (G:\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (G:\blog\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (G:\blog\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (G:\blog\node_modules\bluebird\js\release\async.js:143:10)
INFO  Generating Baidu urls for last 100 posts
INFO  Posts urls generated in baidu_urls.txt
http://www.tiankai.party/hexo+github+域名搭建自己的博客（二）.html
http://www.tiankai.party/hexo-github-域名搭建自己的博客(一).html
http://www.tiankai.party/hello-world.html
http://www.tiankai.party/material.html
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
```

**Comment by tiakia** [comment]
Unhandled rejection TypeError: G:\blog\themes\material\layout\post.ejs:44
    42|                 
    43|                 <% if(page.comment !== false) { %>
 >> 44|                     <%- partial('_partial/comment') %>
    45|                 <% } %>
    46|             </div>
    47|

G:\blog\themes\material\layout\_partial\comment.ejs:1
 >> 1| <% if(theme.comment.use) { %>
    2|     <%- partial('_widget/comment/' + theme.comment.use + '/enter') %>
    3| <% } %>

Cannot read property 'use' of undefined
    at eval (eval at exports.compile (G:\blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:49)
    at eval (eval at exports.compile (G:\blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:204)
    at G:\blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiledSync (G:\blog\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (G:\blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (G:\blog\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (G:\blog\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at exports.compile (G:\blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:1982)
    at eval (eval at exports.compile (G:\blog\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:30:2278)
    at G:\blog\node_modules\ejs\lib\ejs.js:255:15
    at Theme._View.View._compiled (G:\blog\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (G:\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at G:\blog\node_modules\hexo\lib\hexo\index.js:390:25
    at tryCatcher (G:\blog\node_modules\bluebird\js\release\util.js:16:23)
    at G:\blog\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (G:\blog\node_modules\hexo\lib\hexo\router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:429:10)
    at resume_ (_stream_readable.js:809:12)
    at _combinedTickCallback (internal/process/next_tick.js:102:11)
    at process._tickCallback (internal/process/next_tick.js:161:9)

**Comment by tiakia** [comment]
添加时间轴就会报错；一删了就正常了，这是我的 配置文件
# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon.png"   # 网站图标
    high_res_favicon: "/img/favicon-t.jpg"
    apple_touch_icon: "/img/favicon-t.jpg"
    keywords: Web,JS,Hexo,github,react-native
    site_verification:
        google:
        baidu:

    # Enable generate structured-data as JSON+LD for SEO or not.
    #        Set as 'false' if it cause some wrong when `hexo g`.
    structured_data: true

# Jump Links Settings
url:
    rss: 
    daily_pic: "#"
    logo: "#"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme:  Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "我就是我，是颜色不一样的烟火"
    theme_color: "#0097A7"
    theme_sub_color: "#00838F"
    hyperlink_color: "#00838F"
    button_color: "#757575"
    android_chrome_color: "#0097A7"
    nprogress_color: "#29d"
    nprogress_buffer: "800"

# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: true

# Reading experience
reading:
    entry_excerpt: 20

# Thumbnail Settings
thumbnail:
    purecolor:
    random_amount: 19

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#F5F5F5"
    bgimg: "/img/bg.png"
    bing:
        enable: false
        parameter:

# Images Settings
img:
    logo: "/img/logo.png" 
    avatar: "/img/avatar-t.jpg"
    daily_pic: "/img/daily_pic-t.jpg"
    sidebar_header: "/img/sidebar_header-t.jpg"
    random_thumbnail: "/img/random/material-"
    footer_image:
        #upyun_logo:
            #link: "https://www.upyun.com/"
            #src: "/img/upyun_logo.svg"

# Custom Fonts
#   family: the font-family which will be used in the theme
#   host: uri of fonts host.
#       Available value of "host": google | baomitu | ustc | custom
fonts:
    family: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif
    use: baomitu
    custom_font_host:

# Card Elevation Level
card_elevation: 2

# Copyright
# Specify the date when the site was setup.
#   For example, if you set it as 2015, then footer will show '© 2015 - 2017'
copyright_since: 2017

# Qrcode for redirect at other device
#   use: choose which method to generate the qrcode for each posts.
#       Available value of "use": plugin | online
#           - When use "plugin", you need to install the hexo-helper-qrcode.
#           - When use "online", the qrcode will be generated by 'pan.baidu.com' in China.
qrcode:
    enable: false
    use: plugin


# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# TOC Button

toc:
#   use: choose whether the line_number of toc will show or not.
#       Available value of "linenumber": true | false
    linenumber: true

# SNS Menu
sns:
    email: "tiankai0426@sina.com"
    facebook: 
    twitter: 
    googleplus: 
    weibo:
    instagram:
    tumblr:
    github: "https://github.com/tiakia"
    linkedin:
    zhihu:
    bilibili:
    telegram:

# SNS Share Switch
sns_share:
    twitter: true
    facebook: true
    googleplus: false
    weibo: true
    linkedin: false
    qq: true
    telegram: false

# Sidebar Customize
sidebar:
    dropdown:
        Email Me:
            link: "http://m0.mail.sina.com.cn"
            icon: email
    homepage:
        use: true
        icon: home
        divider: false
    archives:
        use: true
        icon: inbox
        divider: false
    categories:
        use: true
        icon: chrome_reader_mode
        divider: false
    pages:
       关于我:
            link: "/about"
            icon: person
            divider: false
        时间轴:
            link: '/timeline'
            icon: send
            divider: false
    article_num:
        use: true
        divider: false
    footer:
        divider: true
        theme: false
        support: false
        feedback: false
        material: false


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# MaterialCDN
# When you set 'use' as true, the needed css, js, font file will have a new src.
# The new src will have the base domain you configured in 'base'.
materialcdn: 
    use: 
    base: 

# Comment Systems
# Available value of "use":
#     disqus | disqus_click | changyan | 163gentie
comment:
    use: 
    shortname: # duoshuo or disqus shortname
    changyan_appid:
    changyan_conf:
    changyan_thread_key_type: path
    gentie_productKey: "https://static.duoshuo.com/embed.js"

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key:

# Analytics Systems
# Available value:
#     baidu | google | cnzz
analytics:
    use: baidu
    site_id: 661158ab1e0fccea66251d60f7dae96a

# Leancloud Views
leancloud:
    enable: false
    app_id: #你的 app_id
    app_key: #你的 app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"

# Busuanzi 不蒜子 Views
busuanzi:
    enable: true
    all_site_uv: true
    post_pv: true
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"

**Comment by neoFelhz** [comment]
你的“时间轴”三个字是不是多打了一个空格？

**Comment by labike** [comment]
source下的tags里面的index.md怎么添加标签云呢？

**Comment by neoFelhz** [comment]
@labike READ THE FUCKING MANUAL, PLEASE.

**Comment by tiakia** [comment]
@neoFelhz  是那个问题，已经解决了 谢谢

**Comment by labike** [comment]
cao  ni ma  de  bu yuan yi  hui da, zhuang ni ma  de  bi!!!
FUCKING YOUR FAMILY!!!
