### ISSUE TITLE
安装时总是提示can not find module...

### ISSUE THREAD

**Issue by Broca-Phenol** [viosey/hexo-theme-material#462]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x ] support request | 请求技术支持

FATAL Cannot find module 'D:\blogs\node_modules\hexo-material'
Error: Cannot find module 'D:\blogs\node_modules\hexo-material'
    at Function.Module._resolveFilename (module.js:485:15)
    at Function.resolve (internal/module.js:18:19)
    at D:\blogs\node_modules\hexo\lib\hexo\load_plugins.js:52:24
    at tryCatcher (D:\blogs\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (D:\blogs\node_modules\bluebird\js\release\map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (D:\blogs\node_modules\bluebird\js\release\promise_array.js:114:31)
    at MappingPromiseArray.init (D:\blogs\node_modules\bluebird\js\release\promise_array.js:78:10)
    at Promise._settlePromise (D:\blogs\node_modules\bluebird\js\release\promise.js:566:21)
    at Promise._settlePromise0 (D:\blogs\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blogs\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\blogs\node_modules\bluebird\js\release\promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (D:\blogs\node_modules\bluebird\js\release\promise_array.js:126:19)
    at MappingPromiseArray._filter (D:\blogs\node_modules\bluebird\js\release\map.js:127:10)
    at MappingPromiseArray._promiseFulfilled (D:\blogs\node_modules\bluebird\js\release\map.js:99:18)
    at Promise._settlePromise (D:\blogs\node_modules\bluebird\js\release\promise.js:574:26)
    at Promise._settlePromise0 (D:\blogs\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blogs\node_modules\bluebird\js\release\promise.js:693:18)
    at Promise._fulfill (D:\blogs\node_modules\bluebird\js\release\promise.js:638:18)
    at Promise._resolveCallback (D:\blogs\node_modules\bluebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (D:\blogs\node_modules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (D:\blogs\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blogs\node_modules\bluebird\js\release\promise.js:614:10)

貌似是之前copy来的js出了问题QAQ

**Comment by neoFelhz** [comment]
Try to delete the line `hexo-material@1.4.0,` in `package.json`.

**Comment by Broca-Phenol** [comment]
@neoFelhz Thanks!!! Problem solved
