### ISSUE TITLE
无法渲染

### ISSUE THREAD

**Issue by mokongh** [viosey/hexo-theme-material#467]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

hexo g         
ERROR Script load failed: themes/material/scripts/helper.js
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:53:16)
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/hexo/index.js:230:17
    at tryCatcher (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:638:18)
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/nodeback.js:42:21
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/graceful-fs/graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
INFO  Start processing
INFO  Files loaded in 261 ms
Unhandled rejection TypeError: /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/post.ejs:44
    42|                 
    43|                 <% if(page.comment !== false) { %>
 >> 44|                     <%- partial('_partial/comment') %>
    45|                 <% } %>
    46|             </div>
    47| 

/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/_partial/comment.ejs:1
 >> 1| <% if(theme.comment.use) { %>
    2|     <%- partial('_widget/comment/' + theme.comment.use + '/enter') %>
    3| <% } %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:9:24)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiledSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:68:17)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiled (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:29:15)
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/util.js:16:23)
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:336:10)
    at resume_ (_stream_readable.js:733:12)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)

Unhandled rejection TypeError: /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/post.ejs:44
    42|                 
    43|                 <% if(page.comment !== false) { %>
 >> 44|                     <%- partial('_partial/comment') %>
    45|                 <% } %>
    46|             </div>
    47| 

/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/_partial/comment.ejs:1
 >> 1| <% if(theme.comment.use) { %>
    2|     <%- partial('_widget/comment/' + theme.comment.use + '/enter') %>
    3| <% } %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:9:24)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiledSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:68:17)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiled (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:29:15)
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/hexo/index.js:390:25
    at tryCatcher (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/util.js:16:23)
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:336:10)
    at resume_ (_stream_readable.js:733:12)
    at nextTickCallbackWith2Args (node.js:458:9)
    at process._tickCallback (node.js:372:17)

Unhandled rejection TypeError: /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         

/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/_partial/head.ejs:39
    37|     
    38|     <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 39|     <% if(theme.materialcdn.use === true) { %>
    40|         <link rel="dns-prefetch" href="<%= theme.materialcdn.base %>"/>
    41|     <%}%>
    42|     <% if(theme.leancloud.enable === true) { %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:46:28)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiledSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiled (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:29:15)
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)

Unhandled rejection TypeError: /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         

/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/_partial/head.ejs:39
    37|     
    38|     <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 39|     <% if(theme.materialcdn.use === true) { %>
    40|         <link rel="dns-prefetch" href="<%= theme.materialcdn.base %>"/>
    41|     <%}%>
    42|     <% if(theme.leancloud.enable === true) { %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:46:28)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiledSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiled (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:29:15)
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)

Unhandled rejection TypeError: /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         

/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/_partial/head.ejs:39
    37|     
    38|     <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 39|     <% if(theme.materialcdn.use === true) { %>
    40|         <link rel="dns-prefetch" href="<%= theme.materialcdn.base %>"/>
    41|     <%}%>
    42|     <% if(theme.leancloud.enable === true) { %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:46:28)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiledSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiled (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:29:15)
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)

Unhandled rejection TypeError: /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         

/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/themes/material/layout/_partial/head.ejs:39
    37|     
    38|     <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 39|     <% if(theme.materialcdn.use === true) { %>
    40|         <link rel="dns-prefetch" href="<%= theme.materialcdn.base %>"/>
    41|     <%}%>
    42|     <% if(theme.leancloud.enable === true) { %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:46:28)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiledSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/ejs/lib/ejs.js:580:17)
    at _compiled (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:29:15)
    at /media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/media/mokong/EABAFBD8BAFB9F6F/MokongGithubWeb/node_modules/bluebird/js/release/async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:396:17)

INFO  Generated: atom.xml
INFO  Generated: sitemap.xml
INFO  Generated: img/avatar.png
INFO  Generated: img/browserstack_logo.png
INFO  Generated: img/favicon.png
INFO  Generated: fonts/MaterialIcons-Regular.woff
INFO  Generated: img/sidebar_header.png
INFO  Generated: img/upyun_logo.svg
INFO  Generated: img/footer/footer_ico-instagram.svg
INFO  Generated: img/footer/footer_ico-gplus.svg
INFO  Generated: img/footer/footer_ico-telegram.svg
INFO  Generated: img/footer/footer_ico-github.svg
INFO  Generated: img/footer/footer_ico-twitter.svg
INFO  Generated: img/footer/footer_ico-facebook.svg
INFO  Generated: img/logo.png
INFO  Generated: img/footer/footer_ico-bilibili.svg
INFO  Generated: img/footer/footer_ico-zhihu.svg
INFO  Generated: img/footer/footer_ico-linkedin.svg
INFO  Generated: img/footer/footer_ico-weibo.svg
INFO  Generated: img/footer/footer_ico-tumblr.svg
INFO  Generated: img/gallery/close.svg
INFO  Generated: img/gallery/spinner.svg
INFO  Generated: img/gallery/arrow.svg
INFO  Generated: img/random/material-12.png
INFO  Generated: img/random/material-17.png
INFO  Generated: img/random/material-19.png
INFO  Generated: img/random/material-3.png
INFO  Generated: img/random/material-6.png
INFO  Generated: img/random/material-8.png
INFO  Generated: img/random/material-9.png
INFO  Generated: img/random/material-4.png
INFO  Generated: img/random/material-10.png
INFO  Generated: img/bg.png
INFO  Generated: fonts/MaterialIcons-Regular.woff2
INFO  Generated: fonts/fontawesome-webfont.woff2
INFO  Generated: fonts/fontawesome-webfont.woff
INFO  Generated: fonts/MaterialIcons-Regular.ttf
INFO  Generated: img/daily_pic.png
INFO  Generated: img/random/material-1.png
INFO  Generated: css/disqus-proxy.min.css
INFO  Generated: css/duoshuo.css
INFO  Generated: css/uc.css
INFO  Generated: css/ie-blocker.css
INFO  Generated: js/ie-blocker.en.js
INFO  Generated: js/ie-blocker.zhCN.js
INFO  Generated: css/duoshuo.min.css
INFO  Generated: js/lsloader.min.js
INFO  Generated: js/lazyload.min.js
INFO  Generated: js/smoothscroll.js
INFO  Generated: js/queue.js
INFO  Generated: js/queue.min.js
INFO  Generated: js/lsloader.js
INFO  Generated: css/fontawesome.min.css
INFO  Generated: css/gallery.min.css
INFO  Generated: css/style.min.css
INFO  Generated: css/disqus-proxy.css
INFO  Generated: css/style.css
INFO  Generated: js/mathjax.js
INFO  Generated: js/jquery.min.js
INFO  Generated: js/nprogress.js
INFO  Generated: js/js.min.js
INFO  Generated: css/material.min.css
INFO  Generated: js/js.js
INFO  Generated: img/random/material-11.png
INFO  Generated: img/random/material-2.png
INFO  Generated: img/random/material-13.png
INFO  Generated: css/material.css
INFO  Generated: img/random/material-18.png
INFO  Generated: img/random/material-16.png
INFO  Generated: img/random/material-7.png
INFO  Generated: img/random/material-5.png
INFO  Generated: img/random/material-14.png
INFO  Generated: fonts/fontawesome-webfont.ttf
INFO  Generated: js/gallery/gallery.js
INFO  Generated: img/random/material-15.png
INFO  Generated: fonts/MaterialIcons-Regular.eot
INFO  Generated: fonts/FontAwesome.otf
INFO  Generated: fonts/fontawesome-webfont.eot
INFO  Generated: fonts/fontawesome-webfont.svg
INFO  Generated: fonts/Roboto-Bold.ttf
INFO  Generated: fonts/Roboto-Black.ttf
INFO  Generated: fonts/Roboto-Medium.ttf
INFO  Generated: fonts/Roboto-Light.ttf
INFO  Generated: fonts/Roboto-Regular.ttf
INFO  Generated: fonts/Roboto-Thin.ttf

**Comment by mokongh** [comment]
是node.js的锅。。。我的Ubuntu一直都是4.2的，不管怎么update都提示最新。卸载后重装就变好了= =
