### ISSUE TITLE
config无法添加时间轴页面单独入口

### ISSUE THREAD

**Issue by Broca-Phenol** [viosey/hexo-theme-material#482]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ x ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ x ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ x ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ x ] support request | 请求技术支持

无法添加时间轴页面，config文件出错...
$ hexo s
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
ERROR Theme config load failed.
ERROR Process failed: _config.yml
Error
    at generateError (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:1080:7)
    at composeNode (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at Object.load (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Hexo.yamlHelper (D:\blogs\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\blogs\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\blogs\node_modules\bluebird\js\release\method.js:15:34)
    at D:\blogs\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (D:\blogs\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blogs\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\blogs\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blogs\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blogs\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\blogs\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\blogs\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\blogs\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
ERROR Theme config load failed.
ERROR Process failed: _config.yml
Error
    at generateError (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:165:10)
    at throwError (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:171:9)
    at readBlockMapping (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:1080:7)
    at composeNode (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:1332:12)
    at readDocument (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:1492:3)
    at loadDocuments (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:1548:5)
    at Object.load (D:\blogs\node_modules\js-yaml\lib\js-yaml\loader.js:1569:19)
    at Hexo.yamlHelper (D:\blogs\node_modules\hexo\lib\plugins\renderer\yaml.js:7:15)
    at Hexo.tryCatcher (D:\blogs\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (D:\blogs\node_modules\bluebird\js\release\method.js:15:34)
    at D:\blogs\node_modules\hexo\lib\hexo\render.js:61:21
    at tryCatcher (D:\blogs\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\blogs\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\blogs\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\blogs\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\blogs\node_modules\bluebird\js\release\promise.js:693:18)
    at Async._drainQueue (D:\blogs\node_modules\bluebird\js\release\async.js:133:16)
    at Async._drainQueues (D:\blogs\node_modules\bluebird\js\release\async.js:143:10)
    at Immediate.Async.drainQueues (D:\blogs\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)

格式 编码都无误啊……

**Comment by neoFelhz** [comment]
Please check you theme config format carefully, there maybe something wrong with it.
