### ISSUE TITLE
页面错误

### ISSUE THREAD

**Issue by betwowt** [viosey/hexo-theme-material#491]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

Unhandled rejection TypeError: /home/app/blog/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         

/home/app/blog/themes/material/layout/_partial/head.ejs:39
    37|     
    38|     <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 39|     <% if(theme.materialcdn.use === true) { %>
    40|         <link rel="dns-prefetch" href="<%= theme.materialcdn.base %>"/>
    41|     <%}%>
    42|     <% if(theme.leancloud.enable === true) { %>

Cannot read property 'use' of undefined
    at eval (eval at <anonymous> (/home/app/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:408)
    at eval (eval at <anonymous> (/home/app/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:49:17999)
    at /home/app/blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiledSync (/home/app/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at View.renderSync (/home/app/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/app/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper (/home/app/blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at <anonymous> (/home/app/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:252)
    at eval (eval at <anonymous> (/home/app/blog/node_modules/ejs/lib/ejs.js:242:14), <anonymous>:30:2468)
    at /home/app/blog/node_modules/ejs/lib/ejs.js:255:15
    at _compiled (/home/app/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at View.render (/home/app/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/app/blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/home/app/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/app/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/app/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/home/app/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/home/app/blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/home/app/blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/home/app/blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/home/app/blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)

**Comment by cubesky** [comment]
@betwowt Do you rename _config.template.yml to _config.yml ?

**Comment by neoFelhz** [comment]
@cubesky Of course not.

**Comment by betwowt** [comment]
问题解决了，但是我想添加豆瓣插件 地址
https://github.com/mythsman/hexo-douban
按照自定义页面的流程。是一个空页面

**Comment by betwowt** [comment]
@cubesky 问题解决了，但是我想添加豆瓣插件 地址
https://github.com/mythsman/hexo-douban
按照自定义页面的流程。是一个空页面

**Comment by cubesky** [comment]
@betwowt 看起来使用这个插件你并不需要创建一个自定义页面，你只需要按照这个插件的配置就可以了

**Comment by betwowt** [comment]
@cubesky WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: movies/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
WARN  No layout: movies/index.html
WARN  No layout: books/index.html
WARN  No layout: books/index.html
报了很多类似于这样的错误。

**Comment by cubesky** [comment]
@betwowt 我刚刚试了下，看起来是这个插件本身的问题

**Comment by betwowt** [comment]
@cubesky 能不能兼容一下呢。这个插件挺喜欢的

**Comment by cubesky** [comment]
@betwowt 我把这个 Issue 关掉，你新开一个 Issue 比较方便我们登记这个问题
