### ISSUE TITLE
ERROR Process failed: layout/_widget/dnsprefetch.ejs

### ISSUE THREAD

**Issue by ZhuangJiayu** [viosey/hexo-theme-material#495]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

今天pull了canary分支后，hexo s报error。之前是canary分支0229c7a

ERROR Process failed: layout/_widget/dnsprefetch.ejs
SyntaxError: Unexpected token || in /mnt/d/Blog/themes/material/layout/_widget/dnsprefetch.ejs while compiling ejs

If the above error is not helpful, you may want to try EJS-Lint:
https://github.com/RyanZim/EJS-Lint
    at new Function (<anonymous>)
    at Template.compile (/mnt/d/Blog/node_modules/ejs/lib/ejs.js:549:12)
    at Object.compile (/mnt/d/Blog/node_modules/ejs/lib/ejs.js:358:16)
    at Function.ejsRenderer.compile (/mnt/d/Blog/node_modules/hexo-renderer-ejs/lib/renderer.js:11:14)
    at Theme._View.View.View._precompile (/mnt/d/Blog/node_modules/hexo/lib/theme/view.js:119:29)
    at Theme._View.View.View (/mnt/d/Blog/node_modules/hexo/lib/theme/view.js:13:8)
    at new Theme._View.View (/mnt/d/Blog/node_modules/hexo/lib/theme/index.js:37:10)
    at Theme.setView (/mnt/d/Blog/node_modules/hexo/lib/theme/index.js:71:20)
    at /mnt/d/Blog/node_modules/hexo/lib/theme/processors/view.js:14:14
    at tryCatcher (/mnt/d/Blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/mnt/d/Blog/node_modules/bluebird/js/release/promise.js:638:18)
    at /mnt/d/Blog/node_modules/bluebird/js/release/nodeback.js:42:21

**Comment by neoFelhz** [comment]
Pull and have a try again?
