### ISSUE TITLE
help.js报错

### ISSUE THREAD

**Issue by lenghonglin** [viosey/hexo-theme-material#501]
clone最新版本，修改配置文件为material主题，但是无法执行

```
F:\leng\blog>hexo s
ERROR Script load failed: themes\material\scripts\helper.js
SyntaxError: Unexpected token ...
    at Object.exports.runInThisContext (vm.js:53:16)
    at F:\leng\blog\node_modules\hexo\lib\hexo\index.js:230:17
    at tryCatcher (F:\leng\blog\node_modules\hexo\node_modules\bluebird\js\relea
se\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\leng\blog\node_modules\hexo\node_mo
dules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\leng\blog\node_modules\hexo\node_modules\blueb
ird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\leng\blog\node_modules\hexo\node_modules\blue
bird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\leng\blog\node_modules\hexo\node_modules\blue
bird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\leng\blog\node_modules\hexo\node_modules\bluebird\js
\release\promise.js:638:18)
    at Promise._resolveCallback (F:\leng\blog\node_modules\hexo\node_modules\blu
ebird\js\release\promise.js:432:57)
    at Promise._settlePromiseFromHandler (F:\leng\blog\node_modules\hexo\node_mo
dules\bluebird\js\release\promise.js:524:17)
    at Promise._settlePromise (F:\leng\blog\node_modules\hexo\node_modules\blueb
ird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\leng\blog\node_modules\hexo\node_modules\blue
bird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\leng\blog\node_modules\hexo\node_modules\blue
bird\js\release\promise.js:693:18)
    at Promise._fulfill (F:\leng\blog\node_modules\hexo\node_modules\bluebird\js
\release\promise.js:638:18)
    at F:\leng\blog\node_modules\hexo\node_modules\bluebird\js\release\nodeback.
js:42:21
    at F:\leng\blog\node_modules\hexo\node_modules\hexo-fs\node_modules\graceful
-fs\graceful-fs.js:78:16
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:380:3)
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: F:\leng\blog\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

F:\leng\blog\themes\material\layout\_partial\head.ejs:19
    17|
    18|     <!-- dns prefetch -->
 >> 19|     <%- partial('_widget/dnsprefetch') %>
    20|
    21|     <!-- Title -->
    22|     <%

F:\leng\blog\themes\material\layout\_widget\dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine
") ) { %>

Cannot read property 'materialcdn' of undefined
    at eval (eval at <anonymous> (F:\leng\blog\node_modules\hexo-renderer-ejs\no
de_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:24)
    at returnedFn (F:\leng\blog\node_modules\hexo-renderer-ejs\node_modules\ejs\
lib\ejs.js:580:17)
    at _compiledSync (F:\leng\blog\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (F:\leng\blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (F:\leng\blog\node_modules\hexo\lib\plugins\helper\partial
.js:42:17)
    at Object.wrapper (F:\leng\blog\node_modules\hexo\node_modules\lodash\lodash
.js:4968:19)
    at eval (eval at <anonymous> (F:\leng\blog\node_modules\hexo-renderer-ejs\no
de_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (F:\leng\blog\node_modules\hexo-renderer-ejs\node_modules\ejs\
lib\ejs.js:580:17)
    at _compiledSync (F:\leng\blog\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (F:\leng\blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (F:\leng\blog\node_modules\hexo\lib\plugins\helper\partial
.js:42:17)
    at Object.wrapper (F:\leng\blog\node_modules\hexo\node_modules\lodash\lodash
.js:4968:19)
    at eval (eval at <anonymous> (F:\leng\blog\node_modules\hexo-renderer-ejs\no
de_modules\ejs\lib\ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (F:\leng\blog\node_modules\hexo-renderer-ejs\node_modules\ejs\
lib\ejs.js:580:17)
    at _compiled (F:\leng\blog\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (F:\leng\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at F:\leng\blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (F:\leng\blog\node_modules\hexo\node_modules\bluebird\js\relea
se\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\leng\blog\node_modules\hexo\node_mo
dules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\leng\blog\node_modules\hexo\node_modules\blueb
ird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\leng\blog\node_modules\hexo\node_modules\blue
bird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\leng\blog\node_modules\hexo\node_modules\blue
bird\js\release\promise.js:693:18)
    at Async._drainQueue (F:\leng\blog\node_modules\hexo\node_modules\bluebird\j
s\release\async.js:133:16)
    at Async._drainQueues (F:\leng\blog\node_modules\hexo\node_modules\bluebird\
js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (F:\leng\blog\node_modules\
hexo\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)

Unhandled rejection TypeError: F:\leng\blog\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

F:\leng\blog\themes\material\layout\_partial\head.ejs:19
    17|
    18|     <!-- dns prefetch -->
 >> 19|     <%- partial('_widget/dnsprefetch') %>
    20|
    21|     <!-- Title -->
    22|     <%

F:\leng\blog\themes\material\layout\_widget\dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine
") ) { %>

Cannot read property 'materialcdn' of undefined
    at eval (eval at <anonymous> (F:\leng\blog\node_modules\hexo-renderer-ejs\no
de_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:24)
    at returnedFn (F:\leng\blog\node_modules\hexo-renderer-ejs\node_modules\ejs\
lib\ejs.js:580:17)
    at _compiledSync (F:\leng\blog\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (F:\leng\blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (F:\leng\blog\node_modules\hexo\lib\plugins\helper\partial
.js:42:17)
    at Object.wrapper (F:\leng\blog\node_modules\hexo\node_modules\lodash\lodash
.js:4968:19)
    at eval (eval at <anonymous> (F:\leng\blog\node_modules\hexo-renderer-ejs\no
de_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (F:\leng\blog\node_modules\hexo-renderer-ejs\node_modules\ejs\
lib\ejs.js:580:17)
    at _compiledSync (F:\leng\blog\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (F:\leng\blog\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (F:\leng\blog\node_modules\hexo\lib\plugins\helper\partial
.js:42:17)
    at Object.wrapper (F:\leng\blog\node_modules\hexo\node_modules\lodash\lodash
.js:4968:19)
    at eval (eval at <anonymous> (F:\leng\blog\node_modules\hexo-renderer-ejs\no
de_modules\ejs\lib\ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (F:\leng\blog\node_modules\hexo-renderer-ejs\node_modules\ejs\
lib\ejs.js:580:17)
    at _compiled (F:\leng\blog\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (F:\leng\blog\node_modules\hexo\lib\theme\view.js:29:15)
    at F:\leng\blog\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (F:\leng\blog\node_modules\hexo\node_modules\bluebird\js\relea
se\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\leng\blog\node_modules\hexo\node_mo
dules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\leng\blog\node_modules\hexo\node_modules\blueb
ird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\leng\blog\node_modules\hexo\node_modules\blue
bird\js\release\promise.js:614:10)
    at Promise._settlePromises (F:\leng\blog\node_modules\hexo\node_modules\blue
bird\js\release\promise.js:693:18)
    at Async._drainQueue (F:\leng\blog\node_modules\hexo\node_modules\bluebird\j
s\release\async.js:133:16)
    at Async._drainQueues (F:\leng\blog\node_modules\hexo\node_modules\bluebird\
js\release\async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (F:\leng\blog\node_modules\
hexo\node_modules\bluebird\js\release\async.js:17:14)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
```

**Comment by cubesky** [comment]
请按照 _config.template.yml 升级你的配置文件

**Comment by bitwater1997** [comment]
我也遇到了这个问题，请问怎么具体怎么解决，是因为的我的配置文件没填满？

**Comment by neoFelhz** [comment]
@bitwater1997 对的。README 中写了，要求 NodeJS 6.0 以上。
