### ISSUE TITLE
Cannot read property 'materialcdn' of undefined

### ISSUE THREAD

**Issue by guawazi** [viosey/hexo-theme-material#502]
Unhandled rejection TypeError: /Users/wangliang/blog/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

/Users/wangliang/blog/themes/material/layout/_partial/head.ejs:19
    17|
    18|     
 >> 19|     <%- partial('_widget/dnsprefetch') %>
    20|
    21|     
    22|     <%

/Users/wangliang/blog/themes/material/layout/_widget/dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>

Cannot read property 'materialcdn' of undefined
    at eval (eval at compile (/Users/wangliang/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:24)
    at returnedFn (/Users/wangliang/blog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/Users/wangliang/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/Users/wangliang/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wangliang/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/Users/wangliang/blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/Users/wangliang/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (/Users/wangliang/blog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/Users/wangliang/blog/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/Users/wangliang/blog/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/Users/wangliang/blog/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/Users/wangliang/blog/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/Users/wangliang/blog/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/Users/wangliang/blog/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled (/Users/wangliang/blog/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/Users/wangliang/blog/node_modules/hexo/lib/theme/view.js:29:15)
    at /Users/wangliang/blog/node_modules/hexo/lib/theme/view.js:40:23
    at tryCatcher (/Users/wangliang/blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/wangliang/blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/wangliang/blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/wangliang/blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/wangliang/blog/node_modules/bluebird/js/release/promise.js:693:18)

**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

**Comment by neoFelhz** [comment]
This is not a bug. It is caused by your wrong config. We won't give any support for you unless you correct your config.

**Comment by sayoojsamuel** [comment]
Whats wrong in config file?
Please suggest the correction. I am new to hexo.
