### ISSUE TITLE
关于更新与node_modules的问题

### ISSUE THREAD

**Issue by hibetterheyj** [viosey/hexo-theme-material#526]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

因为是不是学计算机的，所以有点小白式懵逼，之前更新不知道为什么一直报错，找不到package.json，就瞎更新，在`theme/material`主题下出现了node_modules文件夹。（从上总结一句话，不知道主题下载更新后怎么用，下载解压是应该放到什么文件夹呢？由于是小白，希望文档多一些详细的操作过程。）

今天把之前利用npm命令更新的产生的node_modules手贱删除了，后来在`hexo s`命令下出现了以下报错，但自己实际并未打开qrcode插件服务
```
ERROR Plugin load failed: hexo-helper-qrcode
Error: Cannot find module 'qr-image'
```
与此同时，`hexo s`之后打开的localhost界面出现的是`Cannot GET /`字样，不知如何补救，请求技术支持，谢谢！

**Comment by WoadZS** [comment]
试试重新运行npm install 然后把以前的插件重装一下

**Comment by hibetterheyj** [comment]
@WoadZS 全部重装了一遍，还是显示
```
ERROR Plugin load failed: hexo-helper-qrcode
Error: Cannot find module 'qr-image'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (F:\coding\blog_by_PhilHE\node_modules\hexo\lib\hexo\index.js:216:21)
    at F:\coding\blog_by_PhilHE\node_modules\_hexo-helper-qrcode@1.0.2@hexo-helper-qrcode\index.js:1:82
    at F:\coding\blog_by_PhilHE\node_modules\hexo\lib\hexo\index.js:232:12
    at tryCatcher (F:\coding\blog_by_PhilHE\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (F:\coding\blog_by_PhilHE\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (F:\coding\blog_by_PhilHE\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (F:\coding\blog_by_PhilHE\node_modules\bluebird\js\release\promise.js:614:10)
...
```
不知道是不是要重新`hexo init`重新配置一遍

**Comment by hibetterheyj** [comment]
已解决。将node.js与相关node_modules彻底删除后重新配置。 @neoFelhz 可以考虑关闭，麻烦了！
