### ISSUE TITLE
Cannot find module '/Users/xs/xs/blog/hexo/blog_hexo/node_modules/hexo-material'

### ISSUE THREAD

**Issue by daoSs** [viosey/hexo-theme-material#530]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

在执行 hexo g时会报错
FATAL Cannot find module '/Users/xs/xs/blog/hexo/blog_hexo/node_modules/hexo-material'
Error: Cannot find module '/Users/xs/xs/blog/hexo/blog_hexo/node_modules/hexo-material'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.resolve (internal/module.js:27:19)
    at /Users/xs/xs/blog/hexo/blog_hexo/node_modules/hexo/lib/hexo/load_plugins.js:51:24
    at tryCatcher (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/map.js:61:38)
    at MappingPromiseArray.PromiseArray._iterate (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise_array.js:114:31)
    at MappingPromiseArray.init (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise_array.js:78:10)
    at Promise._settlePromise (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at MappingPromiseArray.PromiseArray._resolve (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise_array.js:126:19)
    at MappingPromiseArray._filter (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/map.js:127:10)
    at MappingPromiseArray._promiseFulfilled (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/map.js:99:18)
    at Promise._settlePromise (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:574:26)
    at Promise._settlePromise0 (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:693:18)
    at Promise._fulfill (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:638:18)
    at Promise._resolveCallback (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:432:57)
    at Promise._settlePromiseFromHandler (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:524:17)
    at Promise._settlePromise (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/xs/xs/blog/hexo/blog_hexo/node_modules/bluebird/js/release/promise.js:614:10)
确定安装过并且确定node_modules 中有hexo-material

**Comment by neoFelhz** [comment]
Try to delete the line `hexo-material@1.5.0` in `package.json` and try again?
