### ISSUE TITLE
更换主题后访问不到localhost:4000，git报错如下

### ISSUE THREAD

**Issue by Mr-houzi** [viosey/hexo-theme-material#538]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

启动server后，访问localhost:4000访问不到，而且git会出现如下错误
$ hexo server
INFO  Start processing
INFO  Hexo is running at http://localhost:4000/. Press Ctrl+C to stop.
Unhandled rejection TypeError: D:\HouziPlanet\houziplanet\themes\material\layout\layout.ejs:3
>>1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
    3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

D:\HouziPlanet\houziplanet\themes\material\layout\_partial\head.ejs:19
>>17|
    18|     
    19|     <%- partial('_widget/dnsprefetch') %>
    20|
    21|     
    22|     <%

D:\HouziPlanet\houziplanet\themes\material\layout\_widget\dnsprefetch.ejs:2
   >>1| <meta http-equiv="x-dns-prefetch-control" content="on">
    2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>

Cannot read property 'materialcdn' of undefined
    at eval (eval at compile (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:24)
    at returnedFn (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiledSync (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (D:\HouziPlanet\houziplanet\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at compile (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiledSync (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (D:\HouziPlanet\houziplanet\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at compile (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiled (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\HouziPlanet\houziplanet\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\HouziPlanet\houziplanet\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\HouziPlanet\houziplanet\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\HouziPlanet\houziplanet\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\HouziPlanet\houziplanet\node_modules\bluebird\js\release\promise.js:693:18)
Unhandled rejection TypeError: D:\HouziPlanet\houziplanet\themes\material\layout\layout.ejs:3
 >> 1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
    3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

D:\HouziPlanet\houziplanet\themes\material\layout\_partial\head.ejs:19
 >> 17|
    18|     
    19|     <%- partial('_widget/dnsprefetch') %>
    20|
    21|     
    22|     <%

D:\HouziPlanet\houziplanet\themes\material\layout\_widget\dnsprefetch.ejs:2
 >> 1| <meta http-equiv="x-dns-prefetch-control" content="on">
    2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>

Cannot read property 'materialcdn' of undefined
    at eval (eval at compile (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:24)
    at returnedFn (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiledSync (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (D:\HouziPlanet\houziplanet\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at compile (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiledSync (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:122:20)
    at Theme._View.View.View.renderSync (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:50:21)
    at Object.partial (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\plugins\helper\partial.js:42:17)
    at Object.wrapper [as partial] (D:\HouziPlanet\houziplanet\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at compile (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (D:\HouziPlanet\houziplanet\node_modules\ejs\lib\ejs.js:580:17)
    at Theme._View.View._compiled (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:127:30)
    at Theme._View.View.View.render (D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:29:15)
    at D:\HouziPlanet\houziplanet\node_modules\hexo\lib\theme\view.js:40:23
    at tryCatcher (D:\HouziPlanet\houziplanet\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\HouziPlanet\houziplanet\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\HouziPlanet\houziplanet\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\HouziPlanet\houziplanet\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\HouziPlanet\houziplanet\node_modules\bluebird\js\release\promise.js:693:18)

**Comment by Mr-houzi** [comment]
更换主题后访问不到localhost:4000，git报错如下

**Comment by huangjj27** [comment]
我觉得楼主可以先调整一下错误代码的格式, 比较难看, 让人难以理解.

**Comment by iiicon** [comment]
确实有问题，其他主题是没有问题的

**Comment by cubesky** [comment]
@iiicon 请按照 _config.template.yml 升级 你的 _config.yml

**Comment by bobby285271** [comment]
@iiicon @Mr-houzi 
亲测在零配置情况下无问题。
附 Travis 构建记录：
初始化博客：
https://travis-ci.org/bobby285271/blog-test/builds/282240192
应用主题：
https://travis-ci.org/bobby285271/blog-test/jobs/282246710

**Comment by Nesive** [comment]
重命名主题内配置文件就好了

**Comment by codevvvv9** [comment]
确实不能用，改名字也不行
