### ISSUE TITLE
links 页无法正确显示

### ISSUE THREAD

**Issue by bobby285271** [viosey/hexo-theme-material#541]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] support request | 请求技术支持
- [ ] feature request | 申请添加新的特性或功能
- [ ] bug report | 反馈一个 bug

已经按照文档要求建立文档：
https://raw.githubusercontent.com/bobby285271/website/master/source/links/index.md
（经测试把第一行的 --- 去掉不是造成此问题的原因，因为我其它页去掉第一行的 --- 一切正常且在此处加上它没有用）
https://raw.githubusercontent.com/bobby285271/website/master/source/_data/links.yml
构建后生成文件：
https://github.com/bobby285271/website/blob/gh-pages/links/index.html
实际效果：
http://www.bobby285271.top/links/
![2017-10-03 17-02-54](https://user-images.githubusercontent.com/20080233/31117522-b9dd350e-a85c-11e7-99aa-db35a2c4767f.png)

**Comment by bobby285271** [comment]
```
$ hexo g
INFO  Start processing
ERROR Process failed: _data/links.yml
YAMLException: bad indentation of a mapping entry at line 18, column 10:
       avatar: https://raw.githubusercontent. ... 
             ^
    at generateError (/home/travis/build/bobby285271/website/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/home/travis/build/bobby285271/website/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/home/travis/build/bobby285271/website/node_modules/js-yaml/lib/js-yaml/loader.js:1080:7)
    at composeNode (/home/travis/build/bobby285271/website/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readBlockMapping (/home/travis/build/bobby285271/website/node_modules/js-yaml/lib/js-yaml/loader.js:1062:11)
    at composeNode (/home/travis/build/bobby285271/website/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/home/travis/build/bobby285271/website/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/home/travis/build/bobby285271/website/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at Object.load (/home/travis/build/bobby285271/website/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Hexo.yamlHelper (/home/travis/build/bobby285271/website/node_modules/hexo/lib/plugins/renderer/yaml.js:7:15)
    at Hexo.tryCatcher (/home/travis/build/bobby285271/website/node_modules/bluebird/js/release/util.js:16:23)
    at Hexo.<anonymous> (/home/travis/build/bobby285271/website/node_modules/bluebird/js/release/method.js:15:34)
    at /home/travis/build/bobby285271/website/node_modules/hexo/lib/hexo/render.js:61:21
    at tryCatcher (/home/travis/build/bobby285271/website/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/home/travis/build/bobby285271/website/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/home/travis/build/bobby285271/website/node_modules/bluebird/js/release/promise.js:569:18)
```
理论上同样的内容，就第 18 行报错是不应该的，然而复现机率 100%

**Comment by bobby285271** [comment]
![2017-10-03 17-53-16](https://user-images.githubusercontent.com/20080233/31119471-c3cfa82e-a863-11e7-9fe2-85379df19d50.png)
![2017-10-03 17-53-19](https://user-images.githubusercontent.com/20080233/31119470-c3cf4e4c-a863-11e7-8a66-078b4bd4419f.png)
调整顺序也没有用

**Comment by bobby285271** [comment]
对了，加引号是没用的，照样报错，指的位置换了一下：
avatar: https://raw.githubusercontent. ... 
^

**Comment by bobby285271** [comment]
考虑干脆像 About 页一样老老实实用 layout: page 算了...

**Comment by bobby285271** [comment]
考虑干脆像 About 页一样老老实实用 layout: page 算了...

**Comment by cubesky** [comment]
@bobby285271 我用你的 link.yml 测试了一下没有发生问题...

**Comment by cubesky** [comment]
![image](https://user-images.githubusercontent.com/8038511/31120262-5ddd7084-a866-11e7-85eb-64e03fe3b209.png)

**Comment by bobby285271** [comment]
@cubesky 
解决。很刁钻的一个文件 + 很刁钻的 Travis。建议在文档补充一下：
1 所有的冒号: 后边都要加一个空格
2 使用空格进行缩进，不要用 tab
（下面这个就是我碰到的问题的解决方案...）
**3 使用 GitHub 自带编辑器，编辑框 line wrap mode 要选择 soft wrap**
