### ISSUE TITLE
运行hexo generate 报Unhandled rejection TypeError:

### ISSUE THREAD

**Issue by cjywoo** [viosey/hexo-theme-material#578]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [x] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ ] support request | 请求技术支持

该主题在部署至travis，时运行 hexo generate报错，以下是报错日志
``` shell
hexo generate
(node:4693) [DEP0061] DeprecationWarning: fs.SyncWriteStream is deprecated.
INFO  Start processing
INFO  Files loaded in 750 ms
Unhandled rejection TypeError: /home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/post.ejs:44
    42|                 <!-- Post Comments -->
    43|                 <% if(page.comment !== false) { %>
 >> 44|                     <%- partial('_partial/comment') %>
    45|                 <% } %>
    46|             </div>
    47| 
/home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/_partial/comment.ejs:1
 >> 1| <% if(theme.comment.use) { %>
    2|     <%- partial('_widget/comment/' + theme.comment.use + '/enter') %>
    3| <% } %>
Cannot read property 'use' of undefined
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:9:25)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:68:17)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:29:15)
    at /home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/hexo/index.js:388:25
    at tryCatcher (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/bluebird/js/release/util.js:16:23)
    at /home/travis/build/cjywoo/cjywoo.github.io/node_modules/bluebird/js/release/method.js:15:34
    at RouteStream._read (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/hexo/router.js:134:3)
    at RouteStream.Readable.read (_stream_readable.js:445:10)
    at resume_ (_stream_readable.js:825:12)
Unhandled rejection TypeError: /home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->
/home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/_partial/head.ejs:20
    18| 
    19|     <!-- dns prefetch -->
 >> 20|     <%- partial('_widget/dnsprefetch') %>
    21| 
    22|     <!-- Meta & Info -->
    23|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
/home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/_widget/dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>
Cannot read property 'materialcdn' of undefined
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:25)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:29:15)
Unhandled rejection TypeError: /home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->
/home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/_partial/head.ejs:20
    18| 
    19|     <!-- dns prefetch -->
 >> 20|     <%- partial('_widget/dnsprefetch') %>
    21| 
    22|     <!-- Meta & Info -->
    23|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
/home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/_widget/dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>
Cannot read property 'materialcdn' of undefined
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:25)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:29:15)
Unhandled rejection TypeError: /home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->
/home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/_partial/head.ejs:20
    18| 
    19|     <!-- dns prefetch -->
 >> 20|     <%- partial('_widget/dnsprefetch') %>
    21| 
    22|     <!-- Meta & Info -->
    23|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
/home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/_widget/dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>
Cannot read property 'materialcdn' of undefined
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:25)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:29:15)
Unhandled rejection TypeError: /home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4| 
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->
/home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/_partial/head.ejs:20
    18| 
    19|     <!-- dns prefetch -->
 >> 20|     <%- partial('_widget/dnsprefetch') %>
    21| 
    22|     <!-- Meta & Info -->
    23|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
/home/travis/build/cjywoo/cjywoo.github.io/themes/material/layout/_widget/dnsprefetch.ejs:2
    1| <meta http-equiv="x-dns-prefetch-control" content="on">
 >> 2| <% if(theme.vendors.materialcdn) { %>
    3|     <link rel="dns-prefetch" href="<%= theme.vendors.materialcdn %>"/>
    4| <% } %>
    5| <% if( (theme.leancloud.enable === true) || (theme.comment.use == "valine") ) { %>
Cannot read property 'materialcdn' of undefined
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:25)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:11:17)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiledSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:122:20)
    at Theme._View.View.View.renderSync (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:50:21)
    at Object.partial (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/plugins/helper/partial.js:42:17)
    at Object.wrapper [as partial] (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/lodash/lodash.js:4968:19)
    at eval (eval at compile (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:549:12), <anonymous>:18:17)
    at returnedFn (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/ejs/lib/ejs.js:580:17)
    at Theme._View.View._compiled (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:127:30)
    at Theme._View.View.View.render (/home/travis/build/cjywoo/cjywoo.github.io/node_modules/hexo/lib/theme/view.js:29:15)
```

**Comment by neoFelhz** [comment]
Remove the `_config.yml` in `.gitignore` of theme directories.

**Comment by cjywoo** [comment]
Thanks

**Comment by cyang812** [comment]
Thanks

**Comment by syokujinau** [comment]
您好，錯誤如下

```
Unhandled rejection TypeError: C:\Users\npr28\Downloads\github\blog\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         <!-- Single Gallery Page -->

C:\Users\npr28\Downloads\github\blog\themes\material\layout\_partial\head.ejs:22
    20|
    21|     <!-- dns prefetch -->
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     <!-- Meta & Info -->
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

C:\Users\npr28\Downloads\github\blog\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
    at eval (eval at compile (C:\Users\npr28\Downloads\github\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:44:36)
    at returnedFn (C:\Users\npr28\Downloads\github\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (C:\Users\npr28\Downloads\github\blog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (C:\Users\npr28\Downloads\github\blog\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (C:\Users\npr28\Downloads\github\blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (C:\Users\npr28\Downloads\github\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:11:17)
    at returnedFn (C:\Users\npr28\Downloads\github\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (C:\Users\npr28\Downloads\github\blog\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (C:\Users\npr28\Downloads\github\blog\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (C:\Users\npr28\Downloads\github\blog\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (C:\Users\npr28\Downloads\github\blog\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:18:17)
    at returnedFn (C:\Users\npr28\Downloads\github\blog\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (C:\Users\npr28\Downloads\github\blog\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (C:\Users\npr28\Downloads\github\blog\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (C:\Users\npr28\Downloads\github\blog\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (C:\Users\npr28\Downloads\github\blog\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (C:\Users\npr28\Downloads\github\blog\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (C:\Users\npr28\Downloads\github\blog\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (C:\Users\npr28\Downloads\github\blog\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (C:\Users\npr28\Downloads\github\blog\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (C:\Users\npr28\Downloads\github\blog\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (C:\Users\npr28\Downloads\github\blog\node_modules\bluebird\js\release\async.js:131:9)

```
主題資料夾的.gitignore刪掉_config.yml還是出現一樣錯誤
