### ISSUE TITLE
hexo g 错误提示

### ISSUE THREAD

**Issue by StevenShiChina** [viosey/hexo-theme-material#583]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

在使用material主题时，使用命令hexo g提示错误如下，也能生成站点文件，也可以使用 localhost:4000 查看本地文件，但这个错误是怎么回事呢，求指点
   ```
$ hexo g
INFO  [hexo-math] Using engine 'mathjax'
INFO  Start processing
INFO  Files loaded in 7.92 s
Unhandled rejection TypeError: F:\github\hexo\themes\material\layout\post.ejs:31
    29|                 <% if(theme.scheme === 'Paradox') { %>
    30|                     <!-- Paradox Post Info -->
 >> 31|                     <%- partial('_partial/Paradox-post-info') %>
    32|                 <% } %>
    33|
    34|                 <!-- Post Content -->

F:\github\hexo\themes\material\layout\_partial\Paradox-post-info.ejs:36
    34|     <ul class="mdl-menu mdl-menu--bottom-right mdl-js-menu mdl-js-ripple                                                                                                                                                             -effect" for="article-functions-viewtags-button">
    35|         <li class="mdl-menu__item">
 >> 36|         <%- list_tags(page.tags, {
    37|             show_count: false,
    38|             class: 'post_tag',
    39|             style: 'none',

name is not a function!
    at TypeError (native)
    at module.exports (F:\github\hexo\node_modules\babel-polyfill\node_modules\c                                                                                                                                                             ore-js\modules\_a-function.js:2:36)
    at Array.sort (F:\github\hexo\node_modules\babel-polyfill\node_modules\core-                                                                                                                                                             js\modules\es6.array.sort.js:21:36)
    at Object.listTagsHelper (F:\github\hexo\node_modules\hexo\lib\plugins\helpe                                                                                                                                                             r\list_tags.js:24:15)
    at Object.wrapper [as list_tags] (F:\github\hexo\node_modules\lodash\lodash.                                                                                                                                                             js:4968:19)
    at eval (eval at <anonymous> (F:\github\hexo\node_modules\ejs\lib\ejs.js:242                                                                                                                                                             :14), <anonymous>:30:1616)
    at eval (eval at <anonymous> (F:\github\hexo\node_modules\ejs\lib\ejs.js:242                                                                                                                                                             :14), <anonymous>:35:177)
    at F:\github\hexo\node_modules\ejs\lib\ejs.js:255:15
    at _compiledSync (F:\github\hexo\node_modules\hexo\lib\theme\view.js:122:20)
    at View.renderSync (F:\github\hexo\node_modules\hexo\lib\theme\view.js:50:21                                                                                                                                                             )
    at Object.partial (F:\github\hexo\node_modules\hexo\lib\plugins\helper\parti                                                                                                                                                             al.js:42:17)
    at Object.wrapper (F:\github\hexo\node_modules\lodash\lodash.js:4968:19)
    at eval (eval at <anonymous> (F:\github\hexo\node_modules\ejs\lib\ejs.js:242                                                                                                                                                             :14), <anonymous>:30:1316)
    at eval (eval at <anonymous> (F:\github\hexo\node_modules\ejs\lib\ejs.js:242                                                                                                                                                             :14), <anonymous>:30:2278)
    at F:\github\hexo\node_modules\ejs\lib\ejs.js:255:15
    at _compiled (F:\github\hexo\node_modules\hexo\lib\theme\view.js:127:30)
    at View.render (F:\github\hexo\node_modules\hexo\lib\theme\view.js:29:15)
    at F:\github\hexo\node_modules\hexo\lib\hexo\index.js:390:25
    at tryCatcher (F:\github\hexo\node_modules\bluebird\js\release\util.js:16:23                                                                                                                                                             )
    at F:\github\hexo\node_modules\bluebird\js\release\method.js:15:34
    at RouteStream._read (F:\github\hexo\node_modules\hexo\lib\hexo\router.js:13                                                                                                                                                             4:3)
    at RouteStream.Readable.read (_stream_readable.js:348:10)
INFO  Generated: baidusitemap.xml
INFO  Generated: atom.xml
INFO  Generated: search.xml
INFO  Generated: sitemap.xml
INFO  Generated: index.html
   ```

**Comment by StevenShiChina** [comment]
如果换做样式 Isolation 则不会报错

**Comment by NimaQu** [comment]
hexo clean试试？我之前也是有类似的报错

**Comment by StevenShiChina** [comment]
试过 hexo clean 还是报错，另外发现以前的公式都不能正常显示，求指点

**Comment by StevenShiChina** [comment]
偷懒的解决方式，将以下代码删除了， 
<% if(page.hide_post_info !== true && theme.scheme === 'Paradox') { %>
                    
                    <%- partial('_partial/Paradox-post-info') %>
                <% } %>
问题就没有了。

**Comment by xianzheTM** [comment]
我遇到了与你类似的错误，我查看了文档后解决了，你看看是不是这个原因;l
为防止造成冲突，主题以 `config.template.yaml` 文件取代 `config.yaml `文件，用以参考配置。 需要手动将 material 文件夹中的 `config.template.yaml `复制一份并重命名为 `config.yaml`。

**Comment by StevenShiChina** [comment]
发现这个主题用的不多，我现在还在用 nexT 主题，想着折腾到 material 上来
