### ISSUE TITLE
hexo g的迷之错误-SyntaxError: Invalid or unexpected token

### ISSUE THREAD

**Issue by WangYifang** [viosey/hexo-theme-material#646]
**我确认我已经查看了** (使用 "x" 选择)

- [x] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [x] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [x] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [x] support request | 请求技术支持

> SunshinedeMacBook-Pro:hexo_blog sunshinepursuer$ sudo hexo g
INFO  Start processing
FATAL Something's wrong. Maybe you can find the solution here: http://hexo.io/docs/troubleshooting.html
Template render error: (unknown path)
  SyntaxError: Invalid or unexpected token
    at Object.exports.prettifyError (/Users/sunshinepursuer/hexo_blog/node_modules/nunjucks/src/lib.js:34:15)
    at new_cls.render (/Users/sunshinepursuer/hexo_blog/node_modules/nunjucks/src/environment.js:472:27)
    at new_cls.renderString (/Users/sunshinepursuer/hexo_blog/node_modules/nunjucks/src/environment.js:328:21)
    at /Users/sunshinepursuer/hexo_blog/node_modules/hexo/lib/extend/tag.js:66:9
    at Promise._execute (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/debuggability.js:303:9)
    at Promise._resolveFromExecutor (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/promise.js:483:18)
    at new Promise (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/promise.js:79:10)
    at Tag.render (/Users/sunshinepursuer/hexo_blog/node_modules/hexo/lib/extend/tag.js:64:10)
    at Object.tagFilter [as onRenderEnd] (/Users/sunshinepursuer/hexo_blog/node_modules/hexo/lib/hexo/post.js:266:16)
    at /Users/sunshinepursuer/hexo_blog/node_modules/hexo/lib/hexo/render.js:65:19
    at tryCatcher (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/sunshinepursuer/hexo_blog/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)

******
发现问题在于一个post的部分内容。只要删除那部分内容，就没有这个问题了。但是我实在是找不出那段内容有啥问题……内容如下：
```
- The results of the user study show that traditional 2D graph visualization are ill suited for immersive environments.

**Comment by MR-zn** [comment]
你解决了吗？我也碰到同样的问题了

**Comment by Tom-Kail** [comment]
我也遇到了

**Comment by En777** [comment]
同样的问题，找到[这篇文章](http://one-more-tech.gitlab.io/develop-notes/2018/06/28/hexo-generate-error--SyntaxError--Invalid-or-unexpected-token/index/)，解决了，搞了好久，这些看不见的字符真烦人
