### ISSUE TITLE
主题安装报错 Cannot read property 'startsWith' of null   

### ISSUE THREAD

**Issue by netyjq** [viosey/hexo-theme-material#711]
按照文档clone下来，复制了`_config.template.yml` 为 `_config.yml`，修改了hexo主题为  `material`，执行 `hexo s --debug` 后，访问 `http://localhost:4000` 就看到这个错误
```
Unhandled rejection TypeError: C:\dev\hexo\themes\material\layout\layout.ejs:3                      
    1| <!DOCTYPE html>                                                                              
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%- config.language.su
 >> 3|     <%- partial('_partial/head') %>                                                          
    4|                                                                                              
    5|     <% if(page.layout === 'gallery') { %>                                                    
    6|         <!-- Single Gallery Page -->                                                         
                                                                                                    
C:\dev\hexo\themes\material\layout\_partial\head.ejs:22                                             
    20|                                                                                             
    21|     <!-- dns prefetch -->                                                                   
 >> 22|     <%- partial('_widget/dnsprefetch') %>                                                   
    23|                                                                                             
    24|     <!-- Meta & Info -->                                                                    
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">                          
                                                                                                    
C:\dev\hexo\themes\material\layout\_widget\dnsprefetch.ejs:12                                       
    10| <% } %>                                                                                     
    11|                                                                                             
 >> 12| <% if(theme.comment.use === "changyan") { %>                                                
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>                             
    14| <% } else if(theme.comment.use === "livere") { %>                                           
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>                           
                                                                                                    
Cannot read property 'startsWith' of null                                                           
    at eval (eval at exports.compile (C:\dev\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:3
    at eval (eval at exports.compile (C:\dev\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:3
    at C:\dev\hexo\node_modules\ejs\lib\ejs.js:255:15                                               
    at Theme._View.View._compiledSync.locals [as _compiledSync] (C:\dev\hexo\node_modules\hexo\lib\t
    at Theme._View.View.View.renderSync (C:\dev\hexo\node_modules\hexo\lib\theme\view.js:49:23)     
    at Object.partial (C:\dev\hexo\node_modules\hexo\lib\plugins\helper\partial.js:38:15)           
    at eval (eval at exports.compile (C:\dev\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:3
    at eval (eval at exports.compile (C:\dev\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:4
    at C:\dev\hexo\node_modules\ejs\lib\ejs.js:255:15                                               
    at Theme._View.View._compiledSync.locals [as _compiledSync] (C:\dev\hexo\node_modules\hexo\lib\t
    at Theme._View.View.View.renderSync (C:\dev\hexo\node_modules\hexo\lib\theme\view.js:49:23)     
    at Object.partial (C:\dev\hexo\node_modules\hexo\lib\plugins\helper\partial.js:38:15)           
    at eval (eval at exports.compile (C:\dev\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:3
    at eval (eval at exports.compile (C:\dev\hexo\node_modules\ejs\lib\ejs.js:242:14), <anonymous>:3
    at C:\dev\hexo\node_modules\ejs\lib\ejs.js:255:15                                               
    at Theme._View.View._compiled.locals [as _compiled] (C:\dev\hexo\node_modules\hexo\lib\theme\vie
    at Theme._View.View.View.render (C:\dev\hexo\node_modules\hexo\lib\theme\view.js:30:15)         
    at _compiled.then.result (C:\dev\hexo\node_modules\hexo\lib\theme\view.js:41:23)                
    at tryCatcher (C:\dev\hexo\node_modules\bluebird\js\release\util.js:16:23)                      
    at Promise._settlePromiseFromHandler (C:\dev\hexo\node_modules\bluebird\js\release\promise.js:51
    at Promise._settlePromise (C:\dev\hexo\node_modules\bluebird\js\release\promise.js:569:18)      
    at Promise._settlePromise0 (C:\dev\hexo\node_modules\bluebird\js\release\promise.js:614:10)     
                                                                                                    
```

**Comment by netyjq** [comment]
解决了，参考 https://github.com/viosey/hexo-theme-material/issues/686#issuecomment-410617760
