### ISSUE TITLE
Error: 

### ISSUE THREAD

**Issue by zzxdzld** [viosey/hexo-theme-material#721]
**I certify that I have first consulted** (check all with "x")

**我确认我已经查看了** (使用 "x" 选择)

- [ x ] [Hexo documentation | Hexo 文档](https://hexo.io/docs/)
- [ x ] [Material theme documentation | Material 主题文档](https://material.viosey.com/)
- [ x ] [Material theme issues | Material 主题的其它 issue](https://github.com/viosey/hexo-theme-material/issues?utf8=%E2%9C%93&q=is%3Aissue)

----

**I'm submitting a**  (check one with "x")

**我正在申请**  (使用 "x" 选择)

- [ ] bug report | 反馈一个 bug
- [ ] feature request | 申请添加新的特性或功能
- [ x ] support request | 请求技术支持

```
ERROR D:\Users\Zheng\Desktop\blogcode\themes\material\layout\layout.ejs:42
    40|                     <%- partial('_partial/footer') %>
    41|
 >> 42|                     <%- partial('_partial/import_js') %>
    43|                 </main>
    44|             </div>
    45|         </body>

D:\Users\Zheng\Desktop\blogcode\themes\material\layout\_partial\import_js.ejs:39
    37|             var inputArea = document.querySelector('#search');
    38|             var getSearchFile = function() {
 >> 39|                 var path = '<%= config.search.path %>';
    40|                 searchFunc(path, 'search', 'local-search-result');
    41|             }
    42|

Cannot read property 'path' of undefined
TypeError: D:\Users\Zheng\Desktop\blogcode\themes\material\layout\layout.ejs:42
    40|                     <%- partial('_partial/footer') %>
    41|
 >> 42|                     <%- partial('_partial/import_js') %>
    43|                 </main>
    44|             </div>
    45|         </body>

D:\Users\Zheng\Desktop\blogcode\themes\material\layout\_partial\import_js.ejs:39
    37|             var inputArea = document.querySelector('#search');
    38|             var getSearchFile = function() {
 >> 39|                 var path = '<%= config.search.path %>';
    40|                 searchFunc(path, 'search', 'local-search-result');
    41|             }
    42|

Cannot read property 'path' of undefined
    at eval (eval at compile (D:\Users\Zheng\Desktop\blogcode\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:86:40)
    at returnedFn (D:\Users\Zheng\Desktop\blogcode\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (D:\Users\Zheng\Desktop\blogcode\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (D:\Users\Zheng\Desktop\blogcode\node_modules\hexo\lib\theme\view.js:49:23)
    at Object.partial (D:\Users\Zheng\Desktop\blogcode\node_modules\hexo\lib\plugins\helper\partial.js:38:15)
    at eval (eval at compile (D:\Users\Zheng\Desktop\blogcode\node_modules\ejs\lib\ejs.js:618:12), <anonymous>:72:17)
    at returnedFn (D:\Users\Zheng\Desktop\blogcode\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (D:\Users\Zheng\Desktop\blogcode\node_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (D:\Users\Zheng\Desktop\blogcode\node_modules\hexo\lib\theme\view.js:30:15)
    at _compiled.then.result (D:\Users\Zheng\Desktop\blogcode\node_modules\hexo\lib\theme\view.js:41:23)
    at tryCatcher (D:\Users\Zheng\Desktop\blogcode\node_modules\bluebird\js\release\util.js:16:23)
    at Promise._settlePromiseFromHandler (D:\Users\Zheng\Desktop\blogcode\node_modules\bluebird\js\release\promise.js:512:31)
    at Promise._settlePromise (D:\Users\Zheng\Desktop\blogcode\node_modules\bluebird\js\release\promise.js:569:18)
    at Promise._settlePromise0 (D:\Users\Zheng\Desktop\blogcode\node_modules\bluebird\js\release\promise.js:614:10)
    at Promise._settlePromises (D:\Users\Zheng\Desktop\blogcode\node_modules\bluebird\js\release\promise.js:694:18)
    at _drainQueueStep (D:\Users\Zheng\Desktop\blogcode\node_modules\bluebird\js\release\async.js:138:12)
    at _drainQueue (D:\Users\Zheng\Desktop\blogcode\node_modules\bluebird\js\release\async.js:131:9)
    at Async._drainQueues (D:\Users\Zheng\Desktop\blogcode\node_modules\bluebird\js\release\async.js:147:5)
    at Immediate.Async.drainQueues [as _onImmediate] (D:\Users\Zheng\Desktop\blogcode\node_modules\bluebird\js\release\async.js:17:14)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

**Comment by DBJDBJ** [comment]
I have the same problem too ...

**Comment by DBJDBJ** [comment]
actually not the same but similar :)

E:\projects\dbjhxo>hexo generate
INFO  Start processing
INFO  Files loaded in 1.43 s
ERROR E:\projects\dbjhxo\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\projects\dbjhxo\themes\material\layout\_partial\head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\projects\dbjhxo\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
TypeError: E:\projects\dbjhxo\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\projects\dbjhxo\themes\material\layout\_partial\head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\projects\dbjhxo\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:44:36)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\projects\dbj
hxo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\projects\dbjhxo\node_modules\hexo\li
b\theme\view.js:49:23)
    at Object.partial (E:\projects\dbjhxo\node_modules\hexo\lib\plugins\helper\p
artial.js:38:15)
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:11:17)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\projects\dbj
hxo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\projects\dbjhxo\node_modules\hexo\li
b\theme\view.js:49:23)
    at Object.partial (E:\projects\dbjhxo\node_modules\hexo\lib\plugins\helper\p
artial.js:38:15)
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:18:17)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (E:\projects\dbjhxo\node
_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\projects\dbjhxo\node_modules\hexo\lib\th
eme\view.js:30:15)
    at _compiled.then.result (E:\projects\dbjhxo\node_modules\hexo\lib\theme\vie
w.js:41:23)
    at tryCatcher (E:\projects\dbjhxo\node_modules\bluebird\js\release\util.js:1
6:23)
    at Promise._settlePromiseFromHandler (E:\projects\dbjhxo\node_modules\bluebi
rd\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\projects\dbjhxo\node_modules\bluebird\js\relea
se\promise.js:569:18)
    at Promise._settlePromise0 (E:\projects\dbjhxo\node_modules\bluebird\js\rele
ase\promise.js:614:10)
    at Promise._settlePromises (E:\projects\dbjhxo\node_modules\bluebird\js\rele
ase\promise.js:694:18)
    at _drainQueueStep (E:\projects\dbjhxo\node_modules\bluebird\js\release\asyn
c.js:138:12)
    at _drainQueue (E:\projects\dbjhxo\node_modules\bluebird\js\release\async.js
:131:9)
ERROR E:\projects\dbjhxo\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\projects\dbjhxo\themes\material\layout\_partial\head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\projects\dbjhxo\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
TypeError: E:\projects\dbjhxo\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\projects\dbjhxo\themes\material\layout\_partial\head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\projects\dbjhxo\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:44:36)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\projects\dbj
hxo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\projects\dbjhxo\node_modules\hexo\li
b\theme\view.js:49:23)
    at Object.partial (E:\projects\dbjhxo\node_modules\hexo\lib\plugins\helper\p
artial.js:38:15)
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:11:17)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\projects\dbj
hxo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\projects\dbjhxo\node_modules\hexo\li
b\theme\view.js:49:23)
    at Object.partial (E:\projects\dbjhxo\node_modules\hexo\lib\plugins\helper\p
artial.js:38:15)
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:18:17)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (E:\projects\dbjhxo\node
_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\projects\dbjhxo\node_modules\hexo\lib\th
eme\view.js:30:15)
    at _compiled.then.result (E:\projects\dbjhxo\node_modules\hexo\lib\theme\vie
w.js:41:23)
    at tryCatcher (E:\projects\dbjhxo\node_modules\bluebird\js\release\util.js:1
6:23)
    at Promise._settlePromiseFromHandler (E:\projects\dbjhxo\node_modules\bluebi
rd\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\projects\dbjhxo\node_modules\bluebird\js\relea
se\promise.js:569:18)
    at Promise._settlePromise0 (E:\projects\dbjhxo\node_modules\bluebird\js\rele
ase\promise.js:614:10)
    at Promise._settlePromises (E:\projects\dbjhxo\node_modules\bluebird\js\rele
ase\promise.js:694:18)
    at _drainQueueStep (E:\projects\dbjhxo\node_modules\bluebird\js\release\asyn
c.js:138:12)
    at _drainQueue (E:\projects\dbjhxo\node_modules\bluebird\js\release\async.js
:131:9)
ERROR E:\projects\dbjhxo\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\projects\dbjhxo\themes\material\layout\_partial\head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\projects\dbjhxo\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
TypeError: E:\projects\dbjhxo\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\projects\dbjhxo\themes\material\layout\_partial\head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\projects\dbjhxo\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:44:36)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\projects\dbj
hxo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\projects\dbjhxo\node_modules\hexo\li
b\theme\view.js:49:23)
    at Object.partial (E:\projects\dbjhxo\node_modules\hexo\lib\plugins\helper\p
artial.js:38:15)
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:11:17)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\projects\dbj
hxo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\projects\dbjhxo\node_modules\hexo\li
b\theme\view.js:49:23)
    at Object.partial (E:\projects\dbjhxo\node_modules\hexo\lib\plugins\helper\p
artial.js:38:15)
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:18:17)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (E:\projects\dbjhxo\node
_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\projects\dbjhxo\node_modules\hexo\lib\th
eme\view.js:30:15)
    at _compiled.then.result (E:\projects\dbjhxo\node_modules\hexo\lib\theme\vie
w.js:41:23)
    at tryCatcher (E:\projects\dbjhxo\node_modules\bluebird\js\release\util.js:1
6:23)
    at Promise._settlePromiseFromHandler (E:\projects\dbjhxo\node_modules\bluebi
rd\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\projects\dbjhxo\node_modules\bluebird\js\relea
se\promise.js:569:18)
    at Promise._settlePromise0 (E:\projects\dbjhxo\node_modules\bluebird\js\rele
ase\promise.js:614:10)
    at Promise._settlePromises (E:\projects\dbjhxo\node_modules\bluebird\js\rele
ase\promise.js:694:18)
    at _drainQueueStep (E:\projects\dbjhxo\node_modules\bluebird\js\release\asyn
c.js:138:12)
    at _drainQueue (E:\projects\dbjhxo\node_modules\bluebird\js\release\async.js
:131:9)
ERROR E:\projects\dbjhxo\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\projects\dbjhxo\themes\material\layout\_partial\head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\projects\dbjhxo\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
TypeError: E:\projects\dbjhxo\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\projects\dbjhxo\themes\material\layout\_partial\head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\projects\dbjhxo\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:44:36)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\projects\dbj
hxo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\projects\dbjhxo\node_modules\hexo\li
b\theme\view.js:49:23)
    at Object.partial (E:\projects\dbjhxo\node_modules\hexo\lib\plugins\helper\p
artial.js:38:15)
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:11:17)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\projects\dbj
hxo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\projects\dbjhxo\node_modules\hexo\li
b\theme\view.js:49:23)
    at Object.partial (E:\projects\dbjhxo\node_modules\hexo\lib\plugins\helper\p
artial.js:38:15)
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:18:17)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (E:\projects\dbjhxo\node
_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\projects\dbjhxo\node_modules\hexo\lib\th
eme\view.js:30:15)
    at _compiled.then.result (E:\projects\dbjhxo\node_modules\hexo\lib\theme\vie
w.js:41:23)
    at tryCatcher (E:\projects\dbjhxo\node_modules\bluebird\js\release\util.js:1
6:23)
    at Promise._settlePromiseFromHandler (E:\projects\dbjhxo\node_modules\bluebi
rd\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\projects\dbjhxo\node_modules\bluebird\js\relea
se\promise.js:569:18)
    at Promise._settlePromise0 (E:\projects\dbjhxo\node_modules\bluebird\js\rele
ase\promise.js:614:10)
    at Promise._settlePromises (E:\projects\dbjhxo\node_modules\bluebird\js\rele
ase\promise.js:694:18)
    at _drainQueueStep (E:\projects\dbjhxo\node_modules\bluebird\js\release\asyn
c.js:138:12)
    at _drainQueue (E:\projects\dbjhxo\node_modules\bluebird\js\release\async.js
:131:9)
ERROR E:\projects\dbjhxo\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\projects\dbjhxo\themes\material\layout\_partial\head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\projects\dbjhxo\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
TypeError: E:\projects\dbjhxo\themes\material\layout\layout.ejs:3
    1| <!DOCTYPE html>
    2| <html style="display: none;" <% if(config.language !== null) { %>lang="<%
- config.language.substring(0,2) %>"<% } %>>
 >> 3|     <%- partial('_partial/head') %>
    4|
    5|     <% if(page.layout === 'gallery') { %>
    6|         

E:\projects\dbjhxo\themes\material\layout\_partial\head.ejs:22
    20|
    21|     
 >> 22|     <%- partial('_widget/dnsprefetch') %>
    23|
    24|     
    25|     <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">

E:\projects\dbjhxo\themes\material\layout\_widget\dnsprefetch.ejs:12
    10| <% } %>
    11|
 >> 12| <% if(theme.comment.use === "changyan") { %>
    13|     <link rel="dns-prefetch" href="https://changyan.sohu.com"/>
    14| <% } else if(theme.comment.use === "livere") { %>
    15|     <link rel="dns-prefetch" href="https://cdn-city.livere.com"/>

Cannot read property 'startsWith' of null
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:44:36)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\projects\dbj
hxo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\projects\dbjhxo\node_modules\hexo\li
b\theme\view.js:49:23)
    at Object.partial (E:\projects\dbjhxo\node_modules\hexo\lib\plugins\helper\p
artial.js:38:15)
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:11:17)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiledSync.locals [as _compiledSync] (E:\projects\dbj
hxo\node_modules\hexo\lib\theme\view.js:121:22)
    at Theme._View.View.View.renderSync (E:\projects\dbjhxo\node_modules\hexo\li
b\theme\view.js:49:23)
    at Object.partial (E:\projects\dbjhxo\node_modules\hexo\lib\plugins\helper\p
artial.js:38:15)
    at eval (eval at compile (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:618
:12), <anonymous>:18:17)
    at returnedFn (E:\projects\dbjhxo\node_modules\ejs\lib\ejs.js:653:17)
    at Theme._View.View._compiled.locals [as _compiled] (E:\projects\dbjhxo\node
_modules\hexo\lib\theme\view.js:125:48)
    at Theme._View.View.View.render (E:\projects\dbjhxo\node_modules\hexo\lib\th
eme\view.js:30:15)
    at _compiled.then.result (E:\projects\dbjhxo\node_modules\hexo\lib\theme\vie
w.js:41:23)
    at tryCatcher (E:\projects\dbjhxo\node_modules\bluebird\js\release\util.js:1
6:23)
    at Promise._settlePromiseFromHandler (E:\projects\dbjhxo\node_modules\bluebi
rd\js\release\promise.js:512:31)
    at Promise._settlePromise (E:\projects\dbjhxo\node_modules\bluebird\js\relea
se\promise.js:569:18)
    at Promise._settlePromise0 (E:\projects\dbjhxo\node_modules\bluebird\js\rele
ase\promise.js:614:10)
    at Promise._settlePromises (E:\projects\dbjhxo\node_modules\bluebird\js\rele
ase\promise.js:694:18)
    at _drainQueueStep (E:\projects\dbjhxo\node_modules\bluebird\js\release\asyn
c.js:138:12)
    at _drainQueue (E:\projects\dbjhxo\node_modules\bluebird\js\release\async.js
:131:9)
INFO  0 files generated in 1.36 s

**Comment by zjt2005** [comment]
Try add a Comment System.(Whether you have or not)
